// Portable-target test (pure Foundation) so the Linux CI leg executes it. The golden fixture was
// generated by scripts/kev/gen-tokenizer-golden.py from the kev-0.5b checkpoint's tokenizer and
// cross-checked there against Hugging Face `tokenizers`; its reduced vocab/merge tables reproduce
// the full tokenizer exactly on the fixture's samples (BPE only ever applies the lowest-ranked
// pair present, so keeping every applied merge at its original rank preserves the trace).
// With ANGLESITE_KEV_ASSETS pointing at a directory holding the checkpoint's vocab.json and
// merges.txt, the same samples also run through the full 151k-entry tables.
import Testing
import Foundation
@testable import AnglesiteCore

@Suite("BytePairEncoder (Kev / Qwen2 tokenizer, #2059)")
struct BytePairEncoderTests {
    struct Golden: Decodable {
        struct Sample: Decodable { let text: String; let ids: [Int32] }
        let pattern: String
        let vocab: [String: Int32]
        let merges: [String]
        let samples: [Sample]
    }

    static func golden() throws -> Golden {
        let url = try #require(Bundle.module.url(forResource: "tokenizer-golden", withExtension: "json", subdirectory: "Fixtures/Kev"))
        return try JSONDecoder().decode(Golden.self, from: Data(contentsOf: url))
    }

    static var assetsDirectory: URL? {
        ProcessInfo.processInfo.environment["ANGLESITE_KEV_ASSETS"].map { URL(fileURLWithPath: $0, isDirectory: true) }
    }

    @Test("the fixture's regex is the encoder's default")
    func patternMatchesFixture() throws {
        #expect(try Self.golden().pattern == BytePairEncoder.qwen2Pattern)
    }

    @Test("reduced tables reproduce every golden sample")
    func reducedTablesMatchGolden() throws {
        let golden = try Self.golden()
        let encoder = try BytePairEncoder(vocabulary: golden.vocab, merges: golden.merges, pattern: golden.pattern)
        for sample in golden.samples {
            #expect(encoder.encode(sample.text) == sample.ids, "text: \(sample.text.debugDescription)")
        }
    }

    @Test("full checkpoint tables reproduce every golden sample", .enabled(if: assetsDirectory != nil))
    func fullTablesMatchGolden() throws {
        let dir = try #require(Self.assetsDirectory)
        let encoder = try BytePairEncoder(
            vocabURL: dir.appendingPathComponent("vocab.json"), mergesURL: dir.appendingPathComponent("merges.txt"))
        #expect(encoder.vocabularySize == 151_643)
        for sample in try Self.golden().samples {
            #expect(encoder.encode(sample.text) == sample.ids, "text: \(sample.text.debugDescription)")
        }
    }

    @Test("empty and whitespace-only input encode to the fixture's ids (never crash)")
    func edgeInputs() throws {
        let golden = try Self.golden()
        let encoder = try BytePairEncoder(vocabulary: golden.vocab, merges: golden.merges)
        #expect(encoder.encode("") == [])
        let space = try #require(golden.samples.first { $0.text == " " })
        #expect(encoder.encode(" ") == space.ids)
    }

    @Test("NFC normalisation makes decomposed and precomposed input encode identically")
    func nfcNormalisation() throws {
        let golden = try Self.golden()
        let encoder = try BytePairEncoder(vocabulary: golden.vocab, merges: golden.merges)
        #expect(encoder.encode("Caf\u{65}\u{301}") == encoder.encode("Caf\u{e9}"))
    }

    @Test("loading rejects a malformed merge line and an incomplete byte alphabet")
    func loadErrors() throws {
        let golden = try Self.golden()
        #expect(throws: BytePairEncoder.LoadError.malformedMerge("onlyone")) {
            _ = try BytePairEncoder(vocabulary: golden.vocab, merges: ["onlyone"])
        }
        var missingByte = golden.vocab
        missingByte["a"] = nil
        #expect(throws: BytePairEncoder.LoadError.incompleteByteAlphabet("a")) {
            _ = try BytePairEncoder(vocabulary: missingByte, merges: [])
        }
        // Comments and blank lines in merges.txt are skipped, not errors.
        _ = try BytePairEncoder(vocabulary: golden.vocab, merges: ["#version: 0.2", "", "a b"])
    }

    @Test("the byte alphabet is the GPT-2 table: 256 distinct single-scalar symbols")
    func byteAlphabet() {
        let table = BytePairEncoder.byteAlphabet
        #expect(table.count == 256)
        #expect(Set(table).count == 256)
        #expect(table.allSatisfy { $0.unicodeScalars.count == 1 })
        #expect(table[Int(UInt8(ascii: "A"))] == "A")
        #expect(table[Int(UInt8(ascii: " "))] == "Ġ")
        #expect(table[0] == "Ā")
    }
}
