import Foundation

/// Ownership marker for the design-interview-generated documents written to a site's `Source/`
/// root (``DesignContextDocument``'s `DESIGN.md`, ``ProductContextDocument``'s `PRODUCT.md`).
///
/// Mirrors `GeneratedEndpoints`'s per-artifact marker + `isOwned` pattern
/// (`Sources/AnglesiteCore/Social/WellKnownInventory.swift`) and the TypeScript
/// `AGENT_SKILLS_MARKER`/`isAgentSkillsDocOwned` pair (`Resources/Template/scripts/agent-skills.ts`),
/// but as a write-time gate for a file that stays **git-tracked** in `Source/` rather than a
/// read-only inventory scan of gitignored build output: ``DesignApplyService`` regenerates the
/// file when it doesn't exist yet or its first line is still this marker, and leaves it alone —
/// with a one-line notice — the moment an owner (or an external agent) has hand-edited it away.
public enum GeneratedDesignDocument {
    /// First line of every document this type governs. Worded differently from
    /// `GeneratedEndpoints.agentSkillsDocMarker` because these regenerate only when a design is
    /// applied, not on every site build.
    public static let marker =
        "<!-- Generated by Anglesite — do not edit; regenerated the next time a design is applied -->"

    /// `true` when `content` is this generator's own prior output — its first line is exactly
    /// ``marker`` — and therefore safe to overwrite. `false` for `nil` (nothing on disk yet is
    /// not "owned", but callers should still write in that case; they check existence
    /// separately) and for any hand-authored content.
    public static func isOwned(_ content: String?) -> Bool {
        guard let content else { return false }
        return content.split(separator: "\n", maxSplits: 1, omittingEmptySubsequences: false).first == marker[...]
    }
}
