import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const menuPage = readFileSync(
  join(root, 'template', 'src', 'pages', 'menu.astro'),
  'utf-8',
);
const slugPage = readFileSync(
  join(root, 'template', 'src', 'pages', 'menu', '[slug].astro'),
  'utf-8',
);

// ---------------------------------------------------------------------------
// Schema.org JSON-LD — menu-specific structured data contracts
// ---------------------------------------------------------------------------
describe('menu Schema.org structured data', () => {
  it('menu.astro uses utility functions for JSON-LD generation', () => {
    // JSON-LD is now generated by imported functions from menu.ts
    expect(menuPage).toContain('generateRestaurantMenusJsonLd');
    expect(menuPage).toContain('generateMenuPageJsonLd');
  });

  it('[slug].astro generates inline Menu → MenuSection → MenuItem hierarchy', () => {
    expect(slugPage).toContain('"@type": "Menu"');
    expect(slugPage).toContain('"@type": "MenuSection"');
    expect(slugPage).toContain('"@type": "MenuItem"');
    expect(slugPage).toContain('hasMenuSection');
    expect(slugPage).toContain('hasMenuItem');
  });

  it('[slug].astro maps dietary tags to schema.org diet URLs', () => {
    const diets = [
      'VegetarianDiet',
      'VeganDiet',
      'GlutenFreeDiet',
      'HalalDiet',
      'KosherDiet',
    ];
    for (const diet of diets) {
      expect(slugPage).toContain(`https://schema.org/${diet}`);
    }
    expect(slugPage).toContain('suitableForDiet');
  });

  it('[slug].astro conditionally includes Offer only when price exists', () => {
    expect(slugPage).toMatch(/if\s*\(i\.data\.price\)/);
    expect(slugPage).toContain('"@type": "Offer"');
  });

  it('menu.astro passes jsonLd to BaseLayout', () => {
    expect(menuPage).toContain('jsonLd=');
  });
});

// ---------------------------------------------------------------------------
// Menu-specific accessibility
// ---------------------------------------------------------------------------
describe('menu accessibility', () => {
  it('menu-selector and menu-nav have descriptive aria-labels', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toMatch(/class="menu-nav"[^>]*aria-label="Menu sections"/);
      expect(page).toMatch(/class="menu-selector"[^>]*aria-label="Menu selection"/);
    }
  });

  it('sections link heading id to aria-labelledby', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toMatch(/aria-labelledby=\{`heading-\$\{/);
      expect(page).toMatch(/id=\{`heading-\$\{/);
    }
  });

  it('[slug].astro marks the active menu link with aria-current', () => {
    expect(slugPage).toMatch(/aria-current=.*"page"/);
  });

  it('dietary badges have aria-label for screen readers', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toMatch(/class="dietary-badge"[^>]*aria-label=/);
    }
  });

  it('dietary labels include contains-alcohol', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toContain('"contains-alcohol"');
    }
  });
});

// ---------------------------------------------------------------------------
// Conditional rendering — menu-specific display logic
// ---------------------------------------------------------------------------
describe('menu conditional rendering', () => {
  it('shows empty state when no menus exist', () => {
    expect(menuPage).toContain('menus.length === 0');
    expect(menuPage).toMatch(/coming soon/i);
  });

  it('menu selector only renders for multiple menus', () => {
    expect(menuPage).toContain('menus.length > 1');
    expect(slugPage).toContain('otherMenus.length > 1');
  });

  it('jump nav only renders for multiple sections', () => {
    expect(menuPage).toContain('allAnchors.length > 1');
    expect(slugPage).toContain('anchors.length > 1');
  });

  it('menu name as h2 only when multiple menus on main page', () => {
    expect(menuPage).toMatch(/menus\.length > 1[\s\S]*?<h2/);
  });

  it('[slug].astro has back link to /menu', () => {
    expect(slugPage).toContain('href="/menu"');
  });

  it('price, image, description, and dietary are conditionally rendered', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toContain('item.data.price &&');
      expect(page).toContain('item.data.image &&');
      expect(page).toContain('item.data.dietary.length > 0');
    }
    expect(menuPage).toContain('menu.data.description &&');
    expect(slugPage).toContain('menu.data.description &&');
  });

  it('filters out unavailable items', () => {
    for (const page of [menuPage, slugPage]) {
      expect(page).toContain('.data.available');
    }
  });
});

// ---------------------------------------------------------------------------
// Multi-menu layout support
// ---------------------------------------------------------------------------
describe('multi-menu layout support', () => {
  it('menu.astro imports inferMenuLayout', () => {
    expect(menuPage).toContain('inferMenuLayout');
  });

  it('menu.astro determines effective layout from menu data or inference', () => {
    expect(menuPage).toContain('effectiveLayout');
  });

  it('menu.astro has tabbed layout markup', () => {
    expect(menuPage).toContain('menu-tabs');
    expect(menuPage).toContain('menu-tab-panel');
  });

  it('menu.astro has pages layout markup with index cards', () => {
    expect(menuPage).toContain('menu-index-grid');
    expect(menuPage).toContain('menu-index-card');
  });

  it('menu.astro supports all three layout modes', () => {
    // Should have conditionals for each layout
    expect(menuPage).toContain('"scroll"');
    expect(menuPage).toContain('"tabs"');
    expect(menuPage).toContain('"pages"');
  });

  it('[slug].astro has cross-links to other menus', () => {
    expect(slugPage).toContain('menu-cross-link');
  });

  it('menu.astro passes data-menu-type on sections', () => {
    expect(menuPage).toContain('data-menu-type');
  });

  it('menu.astro uses Restaurant Schema.org wrapper', () => {
    expect(menuPage).toContain('generateRestaurantMenusJsonLd');
  });
});
