import Foundation

/// The result of running every extraction rung against a snapshot and resolving them into a
/// single, deduplicated set of importable content.
public struct ResolvedContent: Sendable, Equatable {
    /// The resolved import items: one per distinct source URL, highest-priority rung wins,
    /// sorted by publish date descending (`nil` dates last).
    public var items: [ImportItem]

    /// The site's homepage, if a crawled page matched the site's root URL. Never appears in
    /// `items` — the homepage becomes the site's index page, not an importable post/page.
    public var homepage: CapturedPage?

    /// URLs (as crawled, not normalized) of pages that were excluded because they matched an
    /// archive pattern (tag/category/author/search/pagination/feed listing) rather than real
    /// content.
    public var skippedURLs: [String]

    /// Problems collected from every rung during extraction.
    public var problems: [ImportProblem]

    /// Creates a resolved content result with the given items, homepage, skipped URLs, and
    /// problems.
    /// - Parameters:
    ///   - items: The resolved import items.
    ///   - homepage: The site's homepage, if found.
    ///   - skippedURLs: URLs (as crawled) excluded as archive pages.
    ///   - problems: Problems collected from every rung during extraction.
    public init(items: [ImportItem], homepage: CapturedPage?, skippedURLs: [String],
                problems: [ImportProblem]) {
        self.items = items
        self.homepage = homepage
        self.skippedURLs = skippedURLs
        self.problems = problems
    }
}

/// Resolves a crawled `ImportSnapshot` into a single set of import items by running every
/// extraction rung and merging their output.
///
/// The rungs disagree in priority — WordPress's REST API is authoritative when present, a feed
/// is the next-best structured source, and microformats2 markup is the last structured source
/// before falling back to plain-page readability. Rather than have each rung try to detect and
/// defer to the others, `ImportSourceResolver` runs all three unconditionally and merges by
/// source URL, so a WordPress post and its feed entry (or its mf2 h-entry) never produce two
/// items.
public enum ImportSourceResolver {
    /// Path-pattern regexes for pages that are archive/index listings rather than content: tag,
    /// category, and author archives; pagination; and feed-listing URLs. These are automatically
    /// generated by many CMSes (WordPress chief among them) and crawled like any other page, but
    /// they aren't posts or pages a site owner would want imported as content.
    private static let archivePatterns: [NSRegularExpression] = [
        "^/(tag|tags|category|categories|author|page|search)(/|$)",
        "/page/[0-9]+(/|$)$",
        "^/(feed|rss|atom)(\\.|/|$)",
    ].compactMap { try? NSRegularExpression(pattern: $0) }

    /// Runs every extraction rung against `snapshot` and merges their output into a single
    /// deduplicated, sorted result.
    ///
    /// - Parameter snapshot: The crawled site snapshot to resolve.
    /// - Returns: The merged items (rung priority `wpREST > feed > microformats`, plus a
    ///   readability fallback for unclaimed pages), the homepage, skipped archive URLs, and every
    ///   problem collected along the way.
    public static func resolve(_ snapshot: ImportSnapshot) -> ResolvedContent {
        let wpResult = WordPressRESTRung.items(from: snapshot)
        let feedResult = FeedRung.items(from: snapshot)
        let mfResult = MicroformatsRung.items(from: snapshot)
        let problems = wpResult.problems + feedResult.problems + mfResult.problems

        var itemsByURL: [String: ImportItem] = [:]
        for item in wpResult.items + feedResult.items + mfResult.items where itemsByURL[item.sourceURL] == nil {
            itemsByURL[item.sourceURL] = item
        }

        let homepageKey = homepageComparisonKey(for: snapshot.siteURL)
        // A rung can legitimately produce an item for the homepage URL (e.g. a WordPress "page"
        // at the site root) under either trailing-slash form — the homepage never becomes an
        // item regardless of source, so drop every key that resolves to it.
        let homepageItemKeys = itemsByURL.keys.filter { homepageComparisonKey(for: $0) == homepageKey }
        for key in homepageItemKeys { itemsByURL[key] = nil }
        let homepage = snapshot.pages.first {
            homepageComparisonKey(for: $0.extraction.canonical ?? $0.url) == homepageKey
        }

        // Skipped-archive entries keep the page's URL as crawled (not normalized) since they're
        // reported back for the owner's review, not matched against anything further.
        var skippedURLs: [String] = []
        for page in snapshot.pages {
            let key = ImportSnapshot.normalizeURL(page.extraction.canonical ?? page.url)
            guard homepageComparisonKey(for: key) != homepageKey, itemsByURL[key] == nil else { continue }
            let rawPath = URLComponents(string: page.url)?.path ?? ""
            if isArchivePath(rawPath.isEmpty ? "/" : rawPath) {
                skippedURLs.append(page.url)
            } else {
                itemsByURL[key] = readabilityItem(for: page, sourceURL: key)
            }
        }

        // Descending publish date, nil last; ties (including nil/nil) break on sourceURL so the
        // result is deterministic regardless of the backing dictionary's iteration order.
        let items = itemsByURL.values.sorted { lhs, rhs in
            switch (lhs.published, rhs.published) {
            case let (l?, r?):
                return l == r ? lhs.sourceURL < rhs.sourceURL : l > r
            case (nil, nil):
                return lhs.sourceURL < rhs.sourceURL
            case (nil, _):
                return false
            case (_, nil):
                return true
            }
        }

        return ResolvedContent(items: items, homepage: homepage, skippedURLs: skippedURLs,
                               problems: problems)
    }

    /// The comparison key used to test whether a URL is the site's homepage.
    ///
    /// `ImportSnapshot.normalizeURL` only trims an *existing* trailing slash — it never mints
    /// one for a bare host — so `https://example.com` and `https://example.com/` normalize to
    /// two different strings even though they're the same page. This treats an empty path the
    /// same as `/` on top of `normalizeURL` so both forms compare equal. Deliberately not
    /// folded into `ImportSnapshot.normalizeURL` itself (pinned by Task 1's tests) and never
    /// used as an `ImportItem.sourceURL` — only for matching the homepage.
    private static func homepageComparisonKey(for rawURL: String) -> String {
        let normalized = ImportSnapshot.normalizeURL(rawURL)
        guard var components = URLComponents(string: normalized) else { return normalized }
        if components.path.isEmpty {
            components.path = "/"
        }
        return components.string ?? normalized
    }

    /// Whether a URL path matches one of the archive patterns (tag/category/author/search,
    /// pagination, or feed-listing URLs).
    private static func isArchivePath(_ path: String) -> Bool {
        let range = NSRange(path.startIndex..<path.endIndex, in: path)
        return archivePatterns.contains { $0.firstMatch(in: path, range: range) != nil }
    }

    /// Builds a fallback import item straight from a crawled page's extraction record, for pages
    /// no rung claimed.
    private static func readabilityItem(for page: CapturedPage, sourceURL: String) -> ImportItem {
        let extraction = page.extraction
        let published = extraction.publishedISO.flatMap { text in
            iso8601Formatter.date(from: text) ?? iso8601FractionalFormatter.date(from: text)
        }
        return ImportItem(sourceURL: sourceURL, title: extraction.title, published: published,
                          lang: extraction.lang, markdown: extraction.markdown,
                          excerpt: extraction.excerpt, images: extraction.images,
                          rung: .readability, hint: .none)
    }

    private nonisolated(unsafe) static let iso8601Formatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime]
        return formatter
    }()

    private nonisolated(unsafe) static let iso8601FractionalFormatter: ISO8601DateFormatter = {
        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return formatter
    }()
}
