// GENERATED by scripts/kev/bump-kev-assets.sh from scripts/kev/kev-assets.lock.json — do not
// edit by hand. Re-run the script to bump the pin; `scripts/kev/bump-kev-assets.sh --check`
// (CI, linux-build-test lane) fails when this file and the lock disagree.

import Foundation

/// Where the app downloads the Kev-0.5B decision-model assets from, and the SHA-256 digest of
/// the manifest it must find there (#2068, decision D7). `KevModelDownloader` fetches
/// `<baseURL>/MANIFEST.json`, discards it unless its bytes hash to ``manifestSHA256``, and only
/// then downloads the files the manifest lists — each checked against the manifest's own per-file
/// digest and size — so neither the host nor the CDN in front of it is trusted for content, only
/// for availability. The pin moves only through the bump script, as a reviewed commit.
public enum KevModelAssetPin {
    /// Versioned prefix the files are served under; always ends in `/`.
    public static let baseURL = URL(string: "https://anglesite.dwk.io/models/kev-0.5b/")!
    /// Lowercase-hex SHA-256 of the manifest bytes at ``baseURL``. Empty until assets are
    /// published: ``isConfigured`` is then `false` and the app never offers the download.
    public static let manifestSHA256 = ""
    /// ISO-8601 date the pin was last bumped (informational; from the lock).
    public static let pinnedAt = "2026-09-29"
    /// Manifest file name under ``baseURL``.
    public static let manifestPath = "MANIFEST.json"

    /// Whether a manifest digest is pinned at all. With no digest there is nothing to verify
    /// against, so the download is never offered — unverified bytes never reach the model
    /// directory.
    public static var isConfigured: Bool { manifestSHA256.count == 64 }

    /// `<baseURL>/MANIFEST.json`.
    public static var manifestURL: URL { baseURL.appendingPathComponent(manifestPath) }
}
