import Foundation
import AnglesiteSiteModel

/// The generated Cloudflare Worker configuration, `Config/wrangler.toml` (#1960, decision D6).
///
/// Every reader and writer of the file goes through here so its location lives in exactly one
/// place: `SiteScaffolder` writes the static-only starter, `SocialWorkerProvisionTarget`
/// regenerates it with live resource ids, `WorkerNameRename`/`UntitledSitePropagation` rewrite its
/// `name` line, `SocialWorkerProvisionCommand.readPersistedResources` scrapes it back as a
/// recovery source of truth, and `ContainerDeployExecutor`/`ContainerCommandRunner` stage its
/// contents into the guest before every wrangler call that reads configuration.
///
/// The file carries infrastructure identifiers (D1 database ids, KV namespace ids, R2 bucket and
/// queue names) that Anglesite provisions and reconciles on the owner's behalf — app-owned state,
/// not site content — so it is never part of the clonable `Source/` git repo. Sites scaffolded
/// before #1960 kept it at `Source/wrangler.toml`; `DeployStateRelocation` moves that copy on open.
public enum WranglerConfigFile {
    /// `wrangler.toml` — shared with `AnglesitePackage.wranglerConfigFilename`, the layout source of
    /// truth.
    public static let filename = AnglesitePackage.wranglerConfigFilename

    /// The line every site's `.gitignore` carries once migrated, so a copy that reaches the working
    /// tree by any other route (the guest's staged copy, an owner running `wrangler init`) never
    /// enters the repo.
    public static let gitignoreEntry = filename

    private static let gitignoreHeader =
        "# Generated by Anglesite from its own Cloudflare provisioning state; lives in the site package's Config/, not here."

    /// `<configDirectory>/wrangler.toml`.
    public static func url(configDirectory: URL) -> URL {
        configDirectory.appendingPathComponent(filename, isDirectory: false)
    }

    /// `<sourceDirectory>/wrangler.toml` — the pre-#1960 location, read only by
    /// `DeployStateRelocation` (to move it) and by the recovery scrape's last-resort fallback.
    public static func legacyURL(sourceDirectory: URL) -> URL {
        sourceDirectory.appendingPathComponent(filename, isDirectory: false)
    }

    /// The file's contents, or `nil` when it doesn't exist or can't be read as UTF-8.
    public static func read(configDirectory: URL) -> String? {
        try? String(contentsOf: url(configDirectory: configDirectory), encoding: .utf8)
    }

    /// Writes `toml` atomically, creating `Config/` first if a caller reaches this before the
    /// package skeleton did (an imported site, a test fixture).
    public static func write(_ toml: String, configDirectory: URL, fileManager: FileManager = .default) throws {
        try fileManager.createDirectory(at: configDirectory, withIntermediateDirectories: true)
        try toml.write(to: url(configDirectory: configDirectory), atomically: true, encoding: .utf8)
    }

    /// `toml` with its top-level `name = "…"` line replaced by `newName`, or `nil` when there is no
    /// such line to rewrite. Only that one line changes — nothing reconstructs the `[Feature]`
    /// list or provisioned resource blocks from an already-written file, so a full regenerate here
    /// would silently drop social-feature config provisioned before a rename.
    public static func rewritingName(_ newName: String, in toml: String) -> String? {
        var lines = toml.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        guard let index = lines.firstIndex(where: { $0.hasPrefix("name = \"") }) else { return nil }
        lines[index] = "name = \"\(newName)\""
        return lines.joined(separator: "\n")
    }

    /// Adds the header comment and `wrangler.toml` line if the entry isn't already listed on its
    /// own line; returns `contents` byte-for-byte unchanged otherwise. Additive only — mirrors
    /// `SecurityTxtGitignoreSync.addingIgnoreEntry(to:)`, never rewriting unrelated lines.
    public static func addingGitignoreEntry(to contents: String) -> String {
        var lines = contents.isEmpty ? [] : contents.split(separator: "\n", omittingEmptySubsequences: false).map(String.init)
        if lines.last == "" { lines.removeLast() }
        guard !lines.contains(where: { $0.trimmingCharacters(in: .whitespaces) == gitignoreEntry || $0.trimmingCharacters(in: .whitespaces) == "/\(gitignoreEntry)" }) else {
            return contents
        }
        if !lines.isEmpty { lines.append("") }
        lines.append(gitignoreHeader)
        lines.append(gitignoreEntry)
        return lines.joined(separator: "\n") + "\n"
    }
}
