blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/anglesite/anglesite/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 💡 Feature Ideas & Brainstorming
    url: https://github.com/anglesite/anglesite/discussions/categories/ideas
    about: Share feature ideas and brainstorm with other users
  - name: 🆘 Get Help
    url: https://github.com/anglesite/anglesite/discussions/categories/q-a
    about: Get help with using Anglesite or contributing to the project