#!/usr/bin/env npx tsx
/**
 * Agent Skills manifest primitives (#1579, slice 4 of the #1326 Agent Readiness ladder).
 *
 * Publishes `/.well-known/agent-skills/index.json` plus one `SKILL.md` per active skill, per
 * Cloudflare's Agent Skills Discovery RFC (https://github.com/cloudflare/agent-skills-discovery-rfc)
 * — the mechanism its own Agent Readiness scan's `agentSkills` check looks for. See
 * docs/superpowers/specs/2026-08-19-agent-skills-manifest-design.md for the full design.
 *
 * Ownership markers (how a later build tells its own prior output apart from a hand-authored
 * file, mirroring `SECURITY_TXT_MARKER`/`MTA_STS_MARKER` in `edge-artifacts.ts`):
 * - Each `SKILL.md` carries `AGENT_SKILLS_MARKER` as one of its lines.
 * - `index.json` carries an extra `"generator": "anglesite"` top-level field — safe under the
 *   RFC's "clients MUST ignore unrecognized fields" rule.
 */
import { createHash } from "node:crypto";

/** Mirrors `GeneratedEndpoints.agentSkillsDocMarker` in `WellKnownInventory.swift`. */
export const AGENT_SKILLS_MARKER =
  "<!-- Generated by Anglesite — do not edit; this file is regenerated from site config each build -->";

/** Opaque per the RFC — identifies the index schema version; need not resolve. */
export const AGENT_SKILLS_SCHEMA = "https://schemas.agentskills.io/discovery/0.2.0/schema.json";

/** The RFC's skill-name rule: 1–64 chars, lowercase alphanumeric and hyphens, no leading/
 * trailing or doubled hyphen. */
const SKILL_NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export function isValidSkillName(name: string): boolean {
  return name.length >= 1 && name.length <= 64 && SKILL_NAME_PATTERN.test(name);
}

/** `sha256:<64 lowercase hex chars>` of `content`'s raw UTF-8 bytes — the RFC's digest format. */
export function sha256Digest(content: string): string {
  return `sha256:${createHash("sha256").update(content, "utf-8").digest("hex")}`;
}

/** Everything a skill's `body()` needs to render absolute-or-relative task URLs and know which
 * of the four possible skills are actually live for this build. */
export interface AgentSkillsContext {
  siteUrl: string | undefined;
  webmentionEnabled: boolean;
  contactPageExists: boolean;
  bookingPageExists: boolean;
}

export interface AgentSkillDefinition {
  name: string;
  description: string;
  body: (ctx: AgentSkillsContext) => string;
}

/** `${skill.name}/SKILL.md`'s full content: YAML frontmatter, then the ownership marker, then
 * the skill's rendered body. */
export function buildSkillMarkdown(skill: AgentSkillDefinition, ctx: AgentSkillsContext): string {
  return (
    `---\n` +
    `name: ${skill.name}\n` +
    `description: ${skill.description}\n` +
    `---\n` +
    `${AGENT_SKILLS_MARKER}\n\n` +
    `${skill.body(ctx)}`
  );
}

/** `content !== null` and it carries `AGENT_SKILLS_MARKER` as one of its lines — this generator's
 * own prior output, safe to overwrite or delete. */
export function isAgentSkillsDocOwned(content: string | null): boolean {
  return content !== null && content.split("\n").includes(AGENT_SKILLS_MARKER);
}

export interface AgentSkillsIndexEntry {
  name: string;
  description: string;
  url: string;
  digest: string;
}

/** `index.json`'s content for the given active entries, in RFC shape plus the `generator`
 * ownership marker. */
export function buildIndexJson(entries: AgentSkillsIndexEntry[]): string {
  const doc = {
    $schema: AGENT_SKILLS_SCHEMA,
    generator: "anglesite",
    skills: entries.map((entry) => ({
      name: entry.name,
      type: "skill-md",
      description: entry.description,
      url: entry.url,
      digest: entry.digest,
    })),
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/** `content` parses as JSON and its top-level `generator` field is `"anglesite"` — this
 * generator's own prior `index.json`, safe to overwrite. */
export function isAgentSkillsIndexOwned(content: string | null): boolean {
  if (content === null) return false;
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    return false;
  }
  return (
    typeof parsed === "object" &&
    parsed !== null &&
    (parsed as { generator?: unknown }).generator === "anglesite"
  );
}
