/**
 * Agent Skills manifest primitives (#1579, slice 4 of the #1326 Agent Readiness ladder).
 *
 * Publishes `/.well-known/agent-skills/index.json` plus one `SKILL.md` per active skill, per
 * Cloudflare's Agent Skills Discovery RFC (https://github.com/cloudflare/agent-skills-discovery-rfc)
 * — the mechanism its own Agent Readiness scan's `agentSkills` check looks for. See
 * docs/superpowers/specs/2026-08-19-agent-skills-manifest-design.md for the full design.
 *
 * Ownership markers (how a later build tells its own prior output apart from a hand-authored
 * file, mirroring `SECURITY_TXT_MARKER`/`MTA_STS_MARKER` in `edge-artifacts.ts`):
 * - Each `SKILL.md` carries `AGENT_SKILLS_MARKER` as one of its lines.
 * - `index.json` carries an extra `"generator": "anglesite"` top-level field — safe under the
 *   RFC's "clients MUST ignore unrecognized fields" rule.
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

/** Mirrors `GeneratedEndpoints.agentSkillsDocMarker` in `WellKnownInventory.swift`. */
export const AGENT_SKILLS_MARKER =
  "<!-- Generated by Anglesite — do not edit; this file is regenerated from site config each build -->";

/** Opaque per the RFC — identifies the index schema version; need not resolve. */
export const AGENT_SKILLS_SCHEMA = "https://schemas.agentskills.io/discovery/0.2.0/schema.json";

/** The RFC's skill-name rule: 1–64 chars, lowercase alphanumeric and hyphens, no leading/
 * trailing or doubled hyphen. */
const SKILL_NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export function isValidSkillName(name: string): boolean {
  return name.length >= 1 && name.length <= 64 && SKILL_NAME_PATTERN.test(name);
}

/** `sha256:<64 lowercase hex chars>` of `content`'s raw UTF-8 bytes — the RFC's digest format. */
export function sha256Digest(content: string): string {
  return `sha256:${createHash("sha256").update(content, "utf-8").digest("hex")}`;
}

/** Everything a skill's `body()` needs to render absolute-or-relative task URLs and know which
 * of the four possible skills are actually live for this build. */
export interface AgentSkillsContext {
  siteUrl: string | undefined;
  webmentionEnabled: boolean;
  contactPageExists: boolean;
  bookingPageExists: boolean;
}

export interface AgentSkillDefinition {
  name: string;
  description: string;
  body: (ctx: AgentSkillsContext) => string;
}

/** `${skill.name}/SKILL.md`'s full content: YAML frontmatter, then the ownership marker, then
 * the skill's rendered body. */
export function buildSkillMarkdown(skill: AgentSkillDefinition, ctx: AgentSkillsContext): string {
  return (
    `---\n` +
    `name: ${skill.name}\n` +
    `description: ${skill.description}\n` +
    `---\n` +
    `${AGENT_SKILLS_MARKER}\n\n` +
    `${skill.body(ctx)}`
  );
}

/** `content !== null` and it carries `AGENT_SKILLS_MARKER` as one of its lines — this generator's
 * own prior output, safe to overwrite or delete. */
export function isAgentSkillsDocOwned(content: string | null): boolean {
  return content !== null && content.split("\n").includes(AGENT_SKILLS_MARKER);
}

export interface AgentSkillsIndexEntry {
  name: string;
  description: string;
  url: string;
  digest: string;
}

/** `index.json`'s content for the given active entries, in RFC shape plus the `generator`
 * ownership marker. */
export function buildIndexJson(entries: AgentSkillsIndexEntry[]): string {
  const doc = {
    $schema: AGENT_SKILLS_SCHEMA,
    generator: "anglesite",
    skills: entries.map((entry) => ({
      name: entry.name,
      type: "skill-md",
      description: entry.description,
      url: entry.url,
      digest: entry.digest,
    })),
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

/** `content` parses as JSON and its top-level `generator` field is `"anglesite"` — this
 * generator's own prior `index.json`, safe to overwrite. */
export function isAgentSkillsIndexOwned(content: string | null): boolean {
  if (content === null) return false;
  let parsed: unknown;
  try {
    parsed = JSON.parse(content);
  } catch {
    return false;
  }
  return (
    typeof parsed === "object" &&
    parsed !== null &&
    (parsed as { generator?: unknown }).generator === "anglesite"
  );
}

/** `path` rendered against `ctx.siteUrl` when it's a usable HTTPS origin, so an off-site agent
 * gets a URL it can actually fetch; falls back to the bare root-relative path otherwise (mirrors
 * `buildSecurityTxt`'s optional-`siteUrl` handling in `edge-artifacts.ts`). */
function absoluteOrRelative(ctx: AgentSkillsContext, path: string): string {
  if (!ctx.siteUrl) return path;
  try {
    const origin = new URL(ctx.siteUrl);
    return origin.protocol === "https:" ? `${origin.origin}${path}` : path;
  } catch {
    return path;
  }
}

/** The full catalog of visitor-facing tasks this generator knows how to describe. Order is
 * preserved in `index.json`'s `skills` array for stable build output. */
export const AGENT_SKILLS: AgentSkillDefinition[] = [
  {
    name: "subscribe-feed",
    description: "Subscribe to this site's posts via RSS, Atom, or JSON Feed.",
    body: (ctx) =>
      `# Subscribe to this site's feed\n\n` +
      `Fetch one of the feeds below and parse it as the matching format to follow new posts on ` +
      `the visitor's behalf.\n\n` +
      `- RSS: ${absoluteOrRelative(ctx, "/rss.xml")}\n` +
      `- Atom: ${absoluteOrRelative(ctx, "/atom.xml")}\n` +
      `- JSON Feed: ${absoluteOrRelative(ctx, "/feed.json")}\n`,
  },
  {
    name: "send-webmention",
    description:
      "Notify this site of a link to one of its pages — for example a reply or mention — via the Webmention protocol.",
    body: (ctx) =>
      `# Send a Webmention\n\n` +
      `To notify this site that one of its pages was linked to (a reply, like, or mention), send ` +
      `a form-encoded POST request:\n\n` +
      "```\n" +
      `POST ${absoluteOrRelative(ctx, "/webmention")}\n` +
      `Content-Type: application/x-www-form-urlencoded\n\n` +
      `source=<url-that-links-to-target>&target=<url-on-this-site-being-mentioned>\n` +
      "```\n\n" +
      `The \`source\` URL must actually contain a link to \`target\`. This site verifies the link ` +
      `asynchronously; a successful submission returns \`202 Accepted\` and the mention appears ` +
      `once verified.\n`,
  },
  {
    name: "contact-site-owner",
    description: "Send a message to the site owner.",
    body: (ctx) =>
      `# Contact the site owner\n\n` +
      `Visit ${absoluteOrRelative(ctx, "/contact")} and complete the contact form on the visitor's ` +
      `behalf. Confirm the message content and any personal details (name, email) with the ` +
      `visitor before submitting — do not invent or submit values the visitor hasn't provided.\n`,
  },
  {
    name: "book-a-time",
    description: "Book a time with the site owner.",
    body: (ctx) =>
      `# Book a time\n\n` +
      `Visit ${absoluteOrRelative(ctx, "/book")} to view availability and schedule a meeting on ` +
      `the visitor's behalf. Confirm the selected date and time with the visitor before ` +
      `finalizing the booking.\n`,
  },
];

/** Which of `AGENT_SKILLS`' names are actually live for this build. `subscribe-feed` is
 * unconditional — every site has RSS/Atom/JSON Feed routes regardless of content. */
export function activeSkillNames(ctx: AgentSkillsContext): Set<string> {
  const names = new Set<string>(["subscribe-feed"]);
  if (ctx.webmentionEnabled) names.add("send-webmention");
  if (ctx.contactPageExists) names.add("contact-site-owner");
  if (ctx.bookingPageExists) names.add("book-a-time");
  return names;
}

export interface AgentSkillsWriteEntry {
  /** Relative to `.well-known/` — e.g. `"agent-skills/subscribe-feed/SKILL.md"`. */
  path: string;
  content: string;
}

export interface AgentSkillsPlan {
  toWrite: AgentSkillsWriteEntry[];
  /** `.well-known/`-relative `SKILL.md` paths whose skill turned off since the last build and
   * whose on-disk content is still this generator's own — safe to remove. The apply step removes
   * the skill's entire parent directory (not just this file) — a skill-md entry may have other
   * bundled resources colocated with it. */
  toDelete: string[];
}

/**
 * Decides what `/.well-known/agent-skills/` should look like for one build. Pure — no filesystem
 * access — so the activation matrix, digesting, and stale-removal rules are unit-testable without
 * touching disk, mirroring `planSecurityTxt`/`planAtprotoDid` in `edge-artifacts.ts`.
 *
 * `existingSkillMdByName` is each of the four known skills' current `agent-skills/<name>/SKILL.md`
 * content (or `null` if absent) — the caller reads this off disk. A skill that's active this build
 * is always (re)written regardless of what's already there (the same "always regenerate" rule
 * every other config-derived generator in this template follows); the map only matters for the
 * inactive-but-still-present case, to decide whether removal is safe (only this generator's own
 * prior output).
 */
export function planAgentSkills(
  ctx: AgentSkillsContext,
  existingSkillMdByName: Record<string, string | null>,
): AgentSkillsPlan {
  const active = activeSkillNames(ctx);
  const toWrite: AgentSkillsWriteEntry[] = [];
  const toDelete: string[] = [];
  const indexEntries: AgentSkillsIndexEntry[] = [];

  for (const skill of AGENT_SKILLS) {
    const path = `agent-skills/${skill.name}/SKILL.md`;
    if (active.has(skill.name)) {
      const content = buildSkillMarkdown(skill, ctx);
      toWrite.push({ path, content });
      indexEntries.push({
        name: skill.name,
        description: skill.description,
        url: `/.well-known/${path}`,
        digest: sha256Digest(content),
      });
    } else if (isAgentSkillsDocOwned(existingSkillMdByName[skill.name] ?? null)) {
      toDelete.push(path);
    }
  }

  toWrite.push({ path: "agent-skills/index.json", content: buildIndexJson(indexEntries) });
  return { toWrite, toDelete };
}

/** Carries out `planAgentSkills`' decision: reads each known skill's current on-disk content,
 * plans, then writes/removes accordingly. Impure — the fs boundary `main()` calls into, mirroring
 * `applySecurityTxtPlan`/`applyAtprotoDidPlan` in `edge-artifacts.ts`. */
export function applyAgentSkillsPlan(publicDir: string, ctx: AgentSkillsContext): void {
  const wellKnownDir = resolve(publicDir, ".well-known");
  const existingSkillMdByName: Record<string, string | null> = {};
  for (const skill of AGENT_SKILLS) {
    const filePath = resolve(wellKnownDir, "agent-skills", skill.name, "SKILL.md");
    existingSkillMdByName[skill.name] = existsSync(filePath) ? readFileSync(filePath, "utf-8") : null;
  }

  const plan = planAgentSkills(ctx, existingSkillMdByName);

  for (const path of plan.toDelete) {
    rmSync(dirname(resolve(wellKnownDir, path)), { recursive: true, force: true });
    console.log(`Removed stale .well-known/${path.replace(/\/SKILL\.md$/, "/")}`);
  }
  for (const entry of plan.toWrite) {
    const filePath = resolve(wellKnownDir, entry.path);
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, entry.content, "utf-8");
    console.log(`Wrote public/.well-known/${entry.path}`);
  }
}
