#!/usr/bin/env npx tsx
/**
 * Build-time generator for repo-owned edge artifacts: public/robots.txt and
 * public/.well-known/security.txt and public/.well-known/mta-sts.txt. Runs at prebuild (after csp.ts). robots.txt
 * is stable and committed; security.txt carries a per-build Expires and is
 * gitignored (generated only when SECURITY_TXT_MODE resolves to "generated" —
 * see docs/superpowers/specs/2026-07-14-well-known-support-design.md "First
 * implementation: repair security.txt"; originally
 * docs/superpowers/specs/2026-06-27-security-story-hardening-design.md §C1).
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readConfig } from "./config";

// Maintained from https://darkvisitors.com/agents — check periodically for new entries.
export const aiCrawlers = [
  "GPTBot",
  "ChatGPT-User",
  "Google-Extended",
  "anthropic-ai",
  "ClaudeBot",
  "Claude-Web",
  "CCBot",
  "PerplexityBot",
  "Bytespider",
  "Amazonbot",
  "FacebookBot",
  "Applebot-Extended",
  "cohere-ai",
  "Diffbot",
  "ImagesiftBot",
  "Omgilibot",
  "YouBot",
];

/**
 * Parses a raw `CONTENT_SIGNALS` config value (e.g. "search=yes, ai-train=no")
 * into a normalized `Content-Signal` directive value per Cloudflare's Content
 * Signals Policy (https://blog.cloudflare.com/content-signals-policy/).
 * Unrecognized keys/values are dropped rather than emitted verbatim; returns
 * undefined when nothing valid remains, so the directive is omitted.
 */
export function normalizeContentSignal(raw: string | undefined): string | undefined {
  if (!raw) return undefined;
  // Map preserves first-seen key order while letting a later occurrence of the
  // same key overwrite its value, so a typo'd repeat (e.g. "search=yes, search=no")
  // resolves to one unambiguous pair instead of two contradictory ones.
  const pairs = new Map<string, string>();
  for (const part of raw.split(",")) {
    const match = part.trim().match(/^(search|ai-input|ai-train)=(yes|no)$/);
    if (match) pairs.set(match[1], match[2]);
  }
  if (pairs.size === 0) return undefined;
  return [...pairs].map(([key, value]) => `${key}=${value}`).join(", ");
}

/**
 * robots.txt body. Allows all crawlers by default. When `blockAI` is true,
 * appends Disallow directives for known AI training crawlers (#408, C4).
 * `contentSignal` (from `normalizeContentSignal`) adds a `Content-Signal`
 * directive to the default group expressing per-purpose usage preferences.
 * `siteUrl` adds the `Sitemap:` discovery line (#982), emitted only for a valid
 * HTTPS origin on the same terms as security.txt's `Canonical` — an unset,
 * unparseable, or insecure `SITE_URL` omits the line rather than guessing.
 */
export function buildRobotsTxt(
  blockAI = false,
  contentSignal?: string,
  siteUrl?: string,
): string {
  let body = `# robots.txt — generated by scripts/edge-artifacts.ts
User-agent: *
Disallow:
`;
  if (contentSignal) {
    // No leading blank line: under the classic (non-Google) robots.txt grouping
    // convention a blank line ends the current record, which would strand this
    // directive outside the `User-agent: *` group it's meant to apply to.
    body += `# Content Signals — usage preferences for crawlers that honor this directive
# https://blog.cloudflare.com/content-signals-policy/
Content-Signal: ${contentSignal}
`;
  }
  if (blockAI) {
    body += `\n# AI crawler / training bot directives (BLOCK_AI=true in .site-config)\n`;
    for (const bot of aiCrawlers) {
      body += `\nUser-agent: ${bot}\nDisallow: /\n`;
    }
  }
  const origin = httpsOrigin(siteUrl);
  if (origin) {
    // Leading blank line, unlike Content-Signal above: Sitemap is a non-group field, so it must
    // end whichever record precedes it rather than read as a directive belonging to that group.
    body += `\nSitemap: ${origin}/sitemap.xml\n`;
  }
  return body;
}

/** security.txt lifecycle mode. See the design doc's "First implementation: repair security.txt". */
export type SecurityTxtMode = "generated" | "manual" | "disabled";

/**
 * First-line marker identifying output this generator owns. Detecting it is how "generated" mode
 * tells its own prior output apart from a hand-authored file it must never overwrite, and how a
 * mode change knows it's safe to delete only output it actually wrote.
 */
export const SECURITY_TXT_MARKER =
  "# Generated by Anglesite — do not edit; edit SECURITY_CONTACT/.site-config instead (SECURITY_TXT_MODE=generated)";

/** True when `content`'s first line is exactly Anglesite's generated-output marker. */
export function isSecurityTxtMarkerOwned(content: string | null): boolean {
  return content !== null && content.split("\n", 1)[0] === SECURITY_TXT_MARKER;
}

/**
 * Resolves the site's security.txt lifecycle mode. An explicit `SECURITY_TXT_MODE` always wins.
 * When unset — every site scaffolded before this setting existed, or one that hasn't opted in —
 * infer from `SECURITY_CONTACT` alone ("generated" when a usable contact is configured, "disabled"
 * otherwise), matching this generator's pre-existing behavior so an unmigrated site doesn't
 * silently regress. #745 owns writing an explicit mode as part of existing-site migration.
 */
export function resolveSecurityTxtMode(
  modeRaw: string | undefined,
  contact: string | undefined,
): SecurityTxtMode {
  if (modeRaw === "generated" || modeRaw === "manual" || modeRaw === "disabled") return modeRaw;
  return (contact ?? "").trim().length > 0 ? "generated" : "disabled";
}

/**
 * Normalizes a configured contact into an RFC 9116 Contact URI, or null when unusable. A
 * `mailto:`/`tel:` URI is used as-is; a bare email gets a `mailto:` scheme; an `http://` (insecure)
 * web contact is rejected outright — RFC 9116 §2.5 requires a URI, but Anglesite additionally
 * requires HTTPS for web contacts rather than downgrading to a spoofable plaintext channel.
 */
export function normalizeSecurityContact(contact: string | undefined): string | null {
  const trimmed = (contact ?? "").trim();
  if (trimmed.length === 0) return null;
  if (/^https:/i.test(trimmed)) return trimmed;
  if (/^http:/i.test(trimmed)) return null;
  if (/^(mailto:|tel:)/i.test(trimmed)) return trimmed;
  if (trimmed.includes("@")) return `mailto:${trimmed}`;
  return null; // not a URI and not an email — skip rather than emit invalid RFC 9116
}

/** A valid HTTPS absolute URL's origin, or null when `url` is unset, unparseable, or insecure. */
function httpsOrigin(url: string | undefined): string | null {
  if (!url) return null;
  try {
    const parsed = new URL(url);
    return parsed.protocol === "https:" ? parsed.origin : null;
  } catch {
    return null;
  }
}

/**
 * RFC 9116 security.txt body, or null when no usable contact is configured (see
 * `normalizeSecurityContact`). `Expires` is 180 days from `now` — Anglesite product policy,
 * satisfying RFC 9116 §2.5.1's recommendation that it be under a year without treating that
 * recommendation as a MUST. `Canonical` is emitted only for a valid HTTPS `siteUrl`; an unset,
 * unparseable, or insecure `SITE_URL` omits the field rather than falling back to a placeholder
 * origin.
 */
export function buildSecurityTxt(
  contact: string | undefined,
  siteUrl: string | undefined,
  now: Date,
): string | null {
  const contactUri = normalizeSecurityContact(contact);
  if (contactUri === null) return null;
  const expires = new Date(now.getTime() + 180 * 24 * 60 * 60 * 1000).toISOString();
  const origin = httpsOrigin(siteUrl);
  const canonicalLine = origin ? `\nCanonical: ${origin}/.well-known/security.txt` : "";
  return `${SECURITY_TXT_MARKER}\nContact: ${contactUri}\nExpires: ${expires}${canonicalLine}\n`;
}

/** MTA-STS policy modes that Anglesite can publish. `disabled` means no generated policy. */
export type MTAStsMode = "disabled" | "testing" | "enforce";

/** A valid RFC 8461 extension field used solely to identify generator-owned output. */
export const MTA_STS_MARKER = "x-anglesite: generated";

/**
 * Normalizes the comma-separated MX patterns from `MTA_STS_MX`. RFC 8461 allows a DNS
 * hostname or a wildcard in its complete left-most label; Unicode names must be supplied as
 * their DNS/Punycode A-labels. Invalid entries are dropped, and duplicates are collapsed.
 */
export function normalizeMTAStsMX(raw: string | undefined): string[] {
  if (!raw) return [];
  // Keep the final label under the same DNS-label rule as every other label: RFC 8461 requires
  // IDNs to be written as Punycode A-labels, and an A-label TLD can contain hyphens/digits.
  const label = "[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?";
  const domain = `(?:${label}\\.)+${label}`;
  const pattern = new RegExp(`^(?:\\*\\.)?${domain}$`, "i");
  const hosts = new Set<string>();
  for (const part of raw.split(",")) {
    const host = part.trim().replace(/\.$/, "").toLowerCase();
    if (pattern.test(host)) hosts.add(host);
  }
  return [...hosts];
}

export function resolveMTAStsMode(raw: string | undefined): MTAStsMode {
  return raw === "testing" || raw === "enforce" ? raw : "disabled";
}

/**
 * RFC 8461 policy body. The marker is a syntactically-valid extension field, which compliant
 * senders ignore; it lets a later build distinguish its own policy from a hand-authored one.
 * A seven-day max_age gives an owner a practical rollback window while still meeting the RFC's
 * expectation that policies normally live for weeks or longer.
 */
export function buildMTAStsPolicy(mode: MTAStsMode, mxRaw: string | undefined): string | null {
  if (mode === "disabled") return null;
  const mxHosts = normalizeMTAStsMX(mxRaw);
  if (mxHosts.length === 0) return null;
  return `version: STSv1\nmode: ${mode}\n${mxHosts.map((host) => `mx: ${host}`).join("\n")}\nmax_age: 604800\n${MTA_STS_MARKER}\n`;
}

export function isMTAStsMarkerOwned(content: string | null): boolean {
  return content !== null && content.split("\n").some((line) => line === MTA_STS_MARKER);
}

export type MTAStsAction = { kind: "write"; content: string } | { kind: "none" };
export interface MTAStsPlan { action: MTAStsAction; note?: string }

/** Applies the same non-destructive ownership rules as security.txt to the MTA-STS policy. */
export function planMTAStsPolicy(params: {
  mode: MTAStsMode;
  mxRaw: string | undefined;
  existingContent: string | null;
}): MTAStsPlan {
  const { mode, mxRaw, existingContent } = params;
  if (mode === "disabled") {
    return existingContent === null
      ? { action: { kind: "none" } }
      : { action: { kind: "none" }, note: "MTA_STS_MODE=disabled but public/.well-known/mta-sts.txt exists — leaving it in place; remove it or enable MTA-STS." };
  }
  const body = buildMTAStsPolicy(mode, mxRaw);
  if (body === null) {
    return { action: { kind: "none" }, note: `MTA_STS_MODE=${mode} but MTA_STS_MX has no valid MX host — no MTA-STS policy generated.` };
  }
  if (existingContent !== null && !isMTAStsMarkerOwned(existingContent)) {
    return { action: { kind: "none" }, note: "MTA-STS is enabled but public/.well-known/mta-sts.txt is hand-authored — refusing to overwrite it." };
  }
  return { action: { kind: "write", content: body } };
}

/** What `applySecurityTxtPlan` should do to `public/.well-known/security.txt` this build. */
export type SecurityTxtAction =
  | { kind: "write"; content: string }
  | { kind: "delete-stale" }
  | { kind: "none" };

export interface SecurityTxtPlan {
  action: SecurityTxtAction;
  /** Explains a non-trivial outcome (skip, refusal, stale cleanup) in the build log. */
  note?: string;
}

/**
 * Decides what to do with security.txt for one build, given the resolved mode and whatever's
 * already on disk. Pure so the lifecycle rules (ownership, refuse-to-overwrite, contradiction,
 * stale cleanup) are unit-testable without touching the filesystem — `applySecurityTxtPlan`
 * carries out the decision.
 */
export function planSecurityTxt(params: {
  mode: SecurityTxtMode;
  contact: string | undefined;
  siteUrl: string | undefined;
  now: Date;
  existingContent: string | null;
}): SecurityTxtPlan {
  const { mode, contact, siteUrl, now, existingContent } = params;

  if (mode === "disabled") {
    if (existingContent !== null) {
      return {
        action: { kind: "none" },
        note: "SECURITY_TXT_MODE=disabled but public/.well-known/security.txt exists — leaving it in place; resolve the mode/file mismatch (see the pre-deploy report).",
      };
    }
    return { action: { kind: "none" } };
  }

  if (mode === "manual") {
    return { action: { kind: "none" } };
  }

  // generated
  const body = buildSecurityTxt(contact, siteUrl, now);
  const markerOwned = isSecurityTxtMarkerOwned(existingContent);

  if (body === null) {
    if (markerOwned) {
      return {
        action: { kind: "delete-stale" },
        note: "SECURITY_TXT_MODE=generated but SECURITY_CONTACT is unset or unusable — removed the previously generated public/.well-known/security.txt.",
      };
    }
    return {
      action: { kind: "none" },
      note: "SECURITY_TXT_MODE=generated but SECURITY_CONTACT is unset or unusable — no security.txt generated.",
    };
  }

  if (existingContent !== null && !markerOwned) {
    return {
      action: { kind: "none" },
      note: "SECURITY_TXT_MODE=generated but public/.well-known/security.txt already exists and wasn't generated by Anglesite — refusing to overwrite it. Delete the file or set SECURITY_TXT_MODE=manual to adopt it as hand-authored.",
    };
  }

  return { action: { kind: "write", content: body } };
}

function applySecurityTxtPlan(publicDir: string): void {
  const wellKnownDir = resolve(publicDir, ".well-known");
  const filePath = resolve(wellKnownDir, "security.txt");
  const existingContent = existsSync(filePath) ? readFileSync(filePath, "utf-8") : null;
  const plan = planSecurityTxt({
    mode: resolveSecurityTxtMode(readConfig("SECURITY_TXT_MODE"), readConfig("SECURITY_CONTACT")),
    contact: readConfig("SECURITY_CONTACT"),
    siteUrl: readConfig("SITE_URL"),
    now: new Date(),
    existingContent,
  });
  if (plan.note) console.log(plan.note);
  switch (plan.action.kind) {
    case "write":
      mkdirSync(wellKnownDir, { recursive: true });
      writeFileSync(filePath, plan.action.content, "utf-8");
      console.log("Wrote public/.well-known/security.txt");
      break;
    case "delete-stale":
      rmSync(filePath);
      break;
    case "none":
      break;
  }
}

function applyMTAStsPlan(publicDir: string): void {
  const wellKnownDir = resolve(publicDir, ".well-known");
  const filePath = resolve(wellKnownDir, "mta-sts.txt");
  const existingContent = existsSync(filePath) ? readFileSync(filePath, "utf-8") : null;
  const plan = planMTAStsPolicy({
    mode: resolveMTAStsMode(readConfig("MTA_STS_MODE")),
    mxRaw: readConfig("MTA_STS_MX"),
    existingContent,
  });
  if (plan.note) console.log(plan.note);
  if (plan.action.kind === "write") {
    mkdirSync(wellKnownDir, { recursive: true });
    writeFileSync(filePath, plan.action.content, "utf-8");
    console.log("Wrote public/.well-known/mta-sts.txt");
  }
}

function main(): void {
  const publicDir = resolve(process.cwd(), "public");
  const blockAI = (readConfig("BLOCK_AI") ?? "").trim().toLowerCase() === "true";
  const contentSignal = normalizeContentSignal(readConfig("CONTENT_SIGNALS"));
  writeFileSync(
    resolve(publicDir, "robots.txt"),
    buildRobotsTxt(blockAI, contentSignal, readConfig("SITE_URL")),
    "utf-8",
  );
  console.log("Wrote public/robots.txt");

  applySecurityTxtPlan(publicDir);
  applyMTAStsPlan(publicDir);
}

// Run only when invoked directly (e.g. `npx tsx scripts/edge-artifacts.ts`), never on import.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
