// GENERATED by scripts/bump-worker-catalog.sh from scripts/worker-catalog.lock.json — do not
// edit by hand. Re-run the script to bump the pin; `scripts/bump-worker-catalog.sh --check`
// (CI, linux-build-test lane) fails when this file and the lock disagree.

/// The pinned `davidwkeith/workers` commit and the SHA-256 digests of the two manifests the app
/// fetches from it at run time (#1961, decision D7). `WorkerCatalogFetcher` and
/// `WorkersConformanceFetcher` build their URLs from ``commit`` (never a branch name) and refuse
/// a response whose digest doesn't match, so a compromise of that repository's `main` branch —
/// or of the CDN in front of it — can't reach a user's deploy without a deliberate, reviewed bump
/// here. See `docs/architecture.md` ▸ "First-party infrastructure".
public enum WorkerCatalogPin {
    /// GitHub `owner/name` of the monorepo that publishes the manifests.
    public static let repository = "davidwkeith/workers"
    /// The pinned 40-hex commit. Manifests are fetched at this commit, never at a branch.
    public static let commit = "bd0ad3facc5b745ff0bf153f91e70026ace3dfb1"
    /// ISO-8601 date the pin was last bumped (informational; from the lock).
    public static let pinnedAt = "2026-09-09"
    /// Repo-relative path of the worker catalog manifest.
    public static let catalogPath = "catalog.json"
    /// Lowercase-hex SHA-256 of the catalog manifest bytes at ``commit``.
    public static let catalogSHA256 = "84fcd9821391bbc47d991cec67d3ef762b780317d19f191dde2ecb80335fc38f"
    /// Repo-relative path of the conformance status manifest.
    public static let conformanceStatusPath = "conformance/status.json"
    /// Lowercase-hex SHA-256 of the conformance status manifest bytes at ``commit``.
    public static let conformanceStatusSHA256 = "6e1fec25ddc32182130a3640eb9c666a12fc461041df4f3bb82813c71863ad28"
}
