#!/usr/bin/env bash
#
# Pin the Kev-0.5B asset manifest the app downloads on demand (#2068, decision D7 in
# docs/specs/2026-09-08-product-direction-review-decisions.md).
#
# `KevModelDownloader` fetches `<base_url>/MANIFEST.json`, refuses it unless its SHA-256 matches
# the digest pinned here, then downloads every file the verified manifest lists and checks each
# file's own digest and size before anything is moved into
# ~/Library/Application Support/Anglesite/Models/kev-0.5b/. The base URL and the manifest digest
# live in scripts/kev/kev-assets.lock.json (same pattern as scripts/worker-catalog.lock.json),
# and this script is the only thing that bumps them — a deliberate, reviewed step, never
# something the app does on its own. The app reads the pin from the generated
# Sources/AnglesiteCore/AI/Kev/KevModelAssetPin.swift; `--check` fails when it and the lock
# disagree (CI, linux-build-test lane).
#
# Publishing flow (macOS, after scripts/kev/convert-kev-coreml.py wrote <asset-dir>):
#   1. Upload <asset-dir>/* (recursively, preserving the relative paths MANIFEST.json lists) to a
#      *new versioned* prefix under the Anglesite-operated host, e.g.
#      https://anglesite.dwk.io/models/kev-0.5b/2026-09-29/ — never overwrite a prefix the pin
#      has ever pointed at, since an installed app verifies against the digest it shipped with.
#   2. scripts/kev/bump-kev-assets.sh <asset-dir> <base-url>
#   3. Review the printed manifest summary, then commit the lock and the regenerated Swift file
#      together.
#
# Usage:
#   scripts/kev/bump-kev-assets.sh <asset-dir> <base-url>   # pin <asset-dir>/MANIFEST.json served under <base-url>
#   scripts/kev/bump-kev-assets.sh --regenerate             # rewrite KevModelAssetPin.swift from the lock
#   scripts/kev/bump-kev-assets.sh --check                  # verify KevModelAssetPin.swift matches the lock
#
# Overrides (for tests): KEV_ASSETS_LOCK_FILE, KEV_ASSETS_PIN_SWIFT. No network access: the
# digest is computed from the local MANIFEST.json you are about to publish.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

LOCK_FILE="${KEV_ASSETS_LOCK_FILE:-$ROOT/scripts/kev/kev-assets.lock.json}"
PIN_SWIFT="${KEV_ASSETS_PIN_SWIFT:-$ROOT/Sources/AnglesiteCore/AI/Kev/KevModelAssetPin.swift}"
MANIFEST_PATH="MANIFEST.json"

usage() {
    sed -n '/^# Usage:/,/^#$/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

sha256_of() {
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

is_sha256() { [[ "$1" =~ ^[0-9a-f]{64}$ ]]; }
is_date() { [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; }

# lock_read <key> [--allow-empty] — the lock is deliberately flat so sed alone can read it (the
# CI image that runs --check has no jq or python).
lock_read() {
    [[ -f "$LOCK_FILE" ]] || die "missing lock file $LOCK_FILE"
    local value
    value="$(sed -n "s/^[[:space:]]*\"$1\":[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$LOCK_FILE" | head -n 1)"
    if [[ -z "$value" && "${2:-}" != "--allow-empty" ]]; then
        die "lock file $LOCK_FILE has no \"$1\" entry"
    fi
    printf '%s' "$value"
}

validate_lock() {
    local base_url manifest_sha pinned_at
    base_url="$(lock_read base_url)"
    manifest_sha="$(lock_read manifest_sha256 --allow-empty)"
    pinned_at="$(lock_read pinned_at)"
    [[ "$base_url" == https://*/ ]] || die "base_url must be an https URL ending in '/': $base_url"
    [[ -z "$manifest_sha" ]] || is_sha256 "$manifest_sha" || die "manifest_sha256 is not a lowercase 64-hex digest: $manifest_sha"
    is_date "$pinned_at" || die "pinned_at is not YYYY-MM-DD: $pinned_at"
}

render_swift() {
    local base_url manifest_sha pinned_at
    base_url="$(lock_read base_url)"
    manifest_sha="$(lock_read manifest_sha256 --allow-empty)"
    pinned_at="$(lock_read pinned_at)"
    cat <<SWIFT
// GENERATED by scripts/kev/bump-kev-assets.sh from scripts/kev/kev-assets.lock.json — do not
// edit by hand. Re-run the script to bump the pin; \`scripts/kev/bump-kev-assets.sh --check\`
// (CI, linux-build-test lane) fails when this file and the lock disagree.

import Foundation

/// Where the app downloads the Kev-0.5B decision-model assets from, and the SHA-256 digest of
/// the manifest it must find there (#2068, decision D7). \`KevModelDownloader\` fetches
/// \`<baseURL>/MANIFEST.json\`, discards it unless its bytes hash to \`\`manifestSHA256\`\`, and only
/// then downloads the files the manifest lists — each checked against the manifest's own per-file
/// digest and size — so neither the host nor the CDN in front of it is trusted for content, only
/// for availability. The pin moves only through the bump script, as a reviewed commit.
public enum KevModelAssetPin {
    /// Versioned prefix the files are served under; always ends in \`/\`.
    public static let baseURL = URL(string: "$base_url")!
    /// Lowercase-hex SHA-256 of the manifest bytes at \`\`baseURL\`\`. Empty until assets are
    /// published: \`\`isConfigured\`\` is then \`false\` and the app never offers the download.
    public static let manifestSHA256 = "$manifest_sha"
    /// ISO-8601 date the pin was last bumped (informational; from the lock).
    public static let pinnedAt = "$pinned_at"
    /// Manifest file name under \`\`baseURL\`\`.
    public static let manifestPath = "$MANIFEST_PATH"

    /// Whether a manifest digest is pinned at all. With no digest there is nothing to verify
    /// against, so the download is never offered — unverified bytes never reach the model
    /// directory.
    public static var isConfigured: Bool { manifestSHA256.count == 64 }

    /// \`<baseURL>/MANIFEST.json\`.
    public static var manifestURL: URL { baseURL.appendingPathComponent(manifestPath) }
}
SWIFT
}

regenerate() {
    validate_lock
    local tmp
    tmp="$(mktemp)"
    render_swift > "$tmp"
    mv "$tmp" "$PIN_SWIFT"
    echo "wrote $PIN_SWIFT"
}

check() {
    validate_lock
    local expected
    expected="$(render_swift)"
    [[ -f "$PIN_SWIFT" ]] || die "$PIN_SWIFT is missing; run scripts/kev/bump-kev-assets.sh --regenerate"
    if ! diff -u <(printf '%s\n' "$expected") "$PIN_SWIFT" >/dev/null; then
        diff -u <(printf '%s\n' "$expected") "$PIN_SWIFT" || true
        die "$PIN_SWIFT does not match $LOCK_FILE; run scripts/kev/bump-kev-assets.sh --regenerate"
    fi
    echo "OK: $PIN_SWIFT matches $LOCK_FILE"
}

bump() {
    local asset_dir="$1" base_url="$2" manifest
    [[ "$base_url" == https://*/ ]] || die "base-url must be an https URL ending in '/' (a versioned prefix), got: $base_url"
    manifest="$asset_dir/$MANIFEST_PATH"
    [[ -f "$manifest" ]] || die "no $MANIFEST_PATH in $asset_dir (run scripts/kev/convert-kev-coreml.py first)"
    grep -q '"Kev.mlmodelc/' "$manifest" || die "$manifest lists no Kev.mlmodelc/ entries — regenerate it with the current convert-kev-coreml.py, which records every file recursively"
    local digest today
    digest="$(sha256_of "$manifest")"
    today="$(date -u +%Y-%m-%d)"
    cat > "$LOCK_FILE" <<JSON
{
  "_comment": "Pinned download location and SHA-256 digest of the Kev-0.5B asset manifest the app fetches on demand (#2068, decision D7). Written only by scripts/kev/bump-kev-assets.sh, which also regenerates Sources/AnglesiteCore/AI/Kev/KevModelAssetPin.swift from it; scripts/kev/bump-kev-assets.sh --check fails when the two disagree. An empty manifest_sha256 means no assets are published yet: the app then never offers the download. Committed (not gitignored) — this is metadata, not a vendored artifact.",
  "base_url": "$base_url",
  "manifest_path": "$MANIFEST_PATH",
  "manifest_sha256": "$digest",
  "pinned_at": "$today"
}
JSON
    echo "pinned $manifest ($digest) served under $base_url"
    echo "files listed:"
    grep -o '"[^"]*": {"sha256"' "$manifest" | sed 's/: {"sha256"//; s/^/  /' || true
    regenerate
    echo "Now upload the contents of $asset_dir to $base_url (keeping relative paths) and commit the lock + Swift file together."
}

case "${1:-}" in
    --check) check ;;
    --regenerate) regenerate ;;
    -h|--help|"") usage; [[ -n "${1:-}" ]] || exit 1 ;;
    --*) die "unknown option $1" ;;
    *)
        [[ $# -eq 2 ]] || { usage; die "bump needs <asset-dir> <base-url>"; }
        bump "$1" "$2"
        ;;
esac
