/**
 * The site MCP server: a stateless Streamable HTTP endpoint at `/mcp`, gated behind
 * `experimental.mcp` (`worker/mcp-config.json`, generated by `scripts/mcp-artifact.ts`); returns a
 * plain 404 when off, exactly like an unclaimed route.
 *
 * Phase 1 (#1576) shipped three public read-only tools on Cloudflare's `agents` package. Phase 2
 * (#1578) migrates the whole endpoint to `@dwk/mcp` — a dependency-free MCP protocol core built by
 * the same `@dwk/*` package family, whose `createMicropubMcpTools`/`publishPost` adapter is
 * explicitly documented as `@dwk/mcp`'s consumer — so the public and owner-action tool sets share
 * one dispatcher, one `tools/list`, and one auth bridge. See
 * docs/superpowers/specs/2026-08-19-site-mcp-server-design.md (phase 1) and
 * docs/superpowers/specs/2026-08-30-mcp-owner-tools-design.md (phase 2, this migration) for the
 * full design and the reasoning behind the engine change.
 */
import { createMcp, type ToolDefinition } from "@dwk/mcp";
import { createMicropubMcpTools, createMicropubStore, resolveConfig } from "@dwk/micropub";
import { base64url } from "./token-signing.ts";
import { createMcpAuthenticator } from "./mcp-owner-auth.ts";
import { createMicropubMediaMcpTools, createMicropubMediaStore } from "./mcp-media-tools.ts";
import { discoverCollection, generateSlug } from "./post-type-discovery.ts";
import type { WorkerEnv } from "./worker.ts";
import mcpConfigArtifact from "./mcp-config.json";
import type { McpConfigArtifact } from "./mcp-config.ts";
import { htmlToPlainText } from "../src/lib/html-to-plain-text.ts";
import { searchEntries, type McpSearchEntry } from "../src/lib/mcp-search-entries.ts";

const MCP_RATE_LIMIT_WINDOW_SECONDS = 3600;
const MCP_RATE_LIMIT_MAX_PER_WINDOW = 60;

/** Same shape as `worker.ts`'s `consentRateLimitKey`, but its own prefix — MCP tool-call traffic
 *  and IndieAuth consent-form submissions must not share a counter or a threshold. */
export async function mcpRateLimitKey(request: Request): Promise<string> {
  const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip));
  return `mcp-tool-call:${base64url(new Uint8Array(digest)).slice(0, 32)}`;
}

/** Same fail-closed shape as `worker.ts`'s `isConsentRateLimited`: an unbound `SOCIAL_KV` must
 *  never silently disable the limiter. A site with `experimental.mcp` on but no other social
 *  feature active still needs `SOCIAL_KV` provisioned — see `SocialWorkerProvisionCommand`. */
export async function isMcpRateLimited(request: Request, env: WorkerEnv): Promise<boolean> {
  if (!env.SOCIAL_KV) {
    console.warn(JSON.stringify({ event: "mcp.rate_limit_unavailable" }));
    return true;
  }
  const key = await mcpRateLimitKey(request);
  try {
    const raw = await env.SOCIAL_KV.get(key);
    const count = raw ? Number.parseInt(raw, 10) : 0;
    if (count >= MCP_RATE_LIMIT_MAX_PER_WINDOW) return true;
    await env.SOCIAL_KV.put(key, String(count + 1), { expirationTtl: MCP_RATE_LIMIT_WINDOW_SECONDS });
    return false;
  } catch (error) {
    // A KV read/write can fail for reasons an unauthenticated caller controls the volume of —
    // most plausibly the free plan's 1,000 writes/day quota, since `SOCIAL_KV` is shared with
    // IndieAuth. `worker.ts`'s dispatcher has no try/catch around route handlers, so letting this
    // propagate would surface as an uncaught Worker exception (HTTP 1101) rather than a clean
    // 429. Degrade the same way an unbound namespace does: fail closed, never fail open.
    console.warn(JSON.stringify({ event: "mcp.rate_limit_error", error: String(error) }));
    return true;
  }
}

/** Strips a trailing slash (except the bare root) and ensures a leading slash, so `"blog/x/"`,
 *  `"/blog/x"`, and `"/blog/x/"` all resolve to the same asset lookup. */
function normalizePagePath(path: string): string {
  const withLeadingSlash = path.startsWith("/") ? path : `/${path}`;
  return withLeadingSlash.length > 1 && withLeadingSlash.endsWith("/")
    ? withLeadingSlash.slice(0, -1)
    : withLeadingSlash;
}

async function fetchSearchIndex(env: WorkerEnv): Promise<McpSearchEntry[]> {
  if (!env.ASSETS) return [];
  const response = await env.ASSETS.fetch(new Request("https://internal.invalid/mcp-search-index.json"));
  if (!response.ok) return [];
  try {
    // A disabled build still materializes a 0-byte `mcp-search-index.json` (Astro always writes a
    // file for a matched endpoint route), which is a 200 with an unparseable body. Degrade to an
    // empty index rather than throwing, matching `fetchPageContent`'s not-found convention.
    return (await response.json()) as McpSearchEntry[];
  } catch {
    return [];
  }
}

/** For a collection entry, the already-shipped `.md` mirror (`renderMarkdownMirror`,
 *  `[...slug].md.ts`) is tried first; anything else falls back to fetching the built HTML page
 *  and running `htmlToPlainText` on it. Both branches degrade to a plain "not found" string
 *  rather than throwing, matching the WebMCP tools' existing error-shape convention. */
async function fetchPageContent(path: string, env: WorkerEnv): Promise<string> {
  if (!env.ASSETS) return `Not found: ${path}`;
  const normalized = normalizePagePath(path);

  const mdResponse = await env.ASSETS.fetch(new Request(`https://internal.invalid${normalized}.md`));
  if (mdResponse.ok) return mdResponse.text();

  const htmlResponse = await env.ASSETS.fetch(new Request(`https://internal.invalid${normalized}`));
  if (!htmlResponse.ok) return `Not found: ${path}`;
  return htmlToPlainText(await htmlResponse.text());
}

/** The three public read-only tools (#1576), unchanged in behavior from phase 1 — only the
 *  wrapping shape moved from `@modelcontextprotocol/server`'s `registerTool` to `@dwk/mcp`'s
 *  plain-data `ToolDefinition`. `requiredScope: ""` means every caller may call these,
 *  authenticated or not (`ToolRegistry`'s scope check always passes against an empty
 *  requirement). */
function readOnlyToolDefinitions(env: WorkerEnv, config: McpConfigArtifact): ToolDefinition[] {
  return [
    {
      name: "search_posts",
      description: "Search this site's published posts by keyword",
      inputSchema: {
        type: "object",
        properties: {
          query: { type: "string" },
          limit: { type: "number", description: "Max results (1-20, default 5)" },
        },
        required: ["query"],
      },
      requiredScope: "",
      annotations: { readOnlyHint: true },
      async handler(args) {
        const query = typeof args.query === "string" ? args.query : "";
        const limit =
          typeof args.limit === "number" && Number.isFinite(args.limit)
            ? Math.min(Math.max(Math.trunc(args.limit), 1), 20)
            : 5;
        const index = await fetchSearchIndex(env);
        const results = searchEntries(index, query, limit);
        if (results.length === 0) {
          return { content: [{ type: "text", text: `No results for "${query}".` }] };
        }
        const text = results.map((r) => `${r.title} — ${r.url}\n${r.excerpt}`).join("\n\n");
        return { content: [{ type: "text", text }] };
      },
    },
    {
      name: "fetch_page_content",
      description: "Fetch the readable content of one page on this site by its path",
      inputSchema: { type: "object", properties: { path: { type: "string" } }, required: ["path"] },
      requiredScope: "",
      annotations: { readOnlyHint: true },
      async handler(args) {
        const path = typeof args.path === "string" ? args.path : "";
        return { content: [{ type: "text", text: await fetchPageContent(path, env) }] };
      },
    },
    {
      name: "list_feeds",
      description: "List this site's syndication feed URLs",
      inputSchema: { type: "object", properties: {} },
      requiredScope: "",
      annotations: { readOnlyHint: true },
      async handler() {
        return { content: [{ type: "text", text: config.feedPaths.join("\n") }] };
      },
    },
  ];
}

/** Whether this site has Micropub provisioned, matching `handleMicropub`'s own guard — when
 *  false, owner tools are omitted from `tools/list` entirely (never advertised, not just
 *  unreachable behind a scope no token can ever carry). */
function ownerToolsConfigured(env: WorkerEnv): env is WorkerEnv & { MICROPUB_DB: D1Database; MEDIA: R2Bucket } {
  return Boolean(env.MICROPUB_DB && env.MEDIA);
}

function ownerToolDefinitions(env: WorkerEnv & { MICROPUB_DB: D1Database; MEDIA: R2Bucket }, baseUrl: string): ToolDefinition[] {
  const resolvedConfig = resolveConfig({
    baseUrl,
    me: `${baseUrl}/`,
    // Mirrors `handleMicropub`'s `generatePostUrl` exactly (#912) — an MCP-published post lands
    // at the same URL shape as one published through the HTTP endpoint.
    generatePostUrl: (post, commands) => {
      const slug = generateSlug(post, commands);
      const collection = discoverCollection(post);
      return collection ? `${baseUrl}/${collection}/${slug}` : `${baseUrl}/${slug}`;
    },
  });
  const store = createMicropubStore({ MICROPUB_DB: env.MICROPUB_DB });
  const mediaStore = createMicropubMediaStore({ MICROPUB_DB: env.MICROPUB_DB });
  return [
    ...createMicropubMcpTools({ config: resolvedConfig, store }),
    ...createMicropubMediaMcpTools({
      mediaEndpoint: resolvedConfig.mediaEndpoint,
      maxMediaBytes: resolvedConfig.maxMediaBytes,
      media: env.MEDIA,
      store: mediaStore,
    }),
  ];
}

function notFound(): Response {
  return new Response("Not Found", {
    status: 404,
    headers: { "content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff" },
  });
}

/**
 * True when this request's body carries at least one JSON-RPC `tools/call` — the only traffic the
 * `mcp-tool-call:` counter is named for, and the only traffic that costs this Worker an `ASSETS`
 * fetch. Everything else reaching `/mcp` (a bare `HEAD`, which `worker.ts`'s dispatcher mirrors
 * into `GET`; the `initialize`/`notifications/initialized`/`tools/list` handshake; malformed
 * bodies) is answered without a `SOCIAL_KV.put`, so an unauthenticated caller can no longer
 * amplify one request into one KV write against a namespace shared with IndieAuth.
 *
 * Reads `request.clone()` so the real handler still receives an unconsumed body. A body that
 * doesn't parse is not a tool call: it does no asset fetch and gets rejected by the MCP handler,
 * so declining to meter it grants no useful capability.
 */
export async function isMcpToolCallRequest(request: Request): Promise<boolean> {
  if (request.method !== "POST") return false;
  try {
    const payload: unknown = await request.clone().json();
    const messages = Array.isArray(payload) ? payload : [payload];
    return messages.some((m) => (m as { method?: unknown } | null)?.method === "tools/call");
  } catch {
    return false;
  }
}

/** Factory so tests can inject a config independent of the real build-time artifact — see
 *  `worker/worker.test.ts`. `handleMcp` below is the production handler, bound to the real
 *  generated `mcp-config.json`. The limiter runs only for `tools/call` traffic (see
 *  `isMcpToolCallRequest`), so the fail-closed-when-`SOCIAL_KV`-is-unbound rule now guards the
 *  tools rather than the handshake: `initialize`/`tools/list` do no asset fetch and no KV write,
 *  and metering them bought nothing but write amplification. */
export function createHandleMcp(config: McpConfigArtifact) {
  return async function handleMcp(request: Request, env: WorkerEnv, _ctx: ExecutionContext): Promise<Response> {
    if (!config.enabled) return notFound();
    if ((await isMcpToolCallRequest(request)) && (await isMcpRateLimited(request, env))) {
      return new Response("Too Many Requests", { status: 429 });
    }
    const baseUrl = new URL(request.url).origin;
    const tools = ownerToolsConfigured(env)
      ? [...readOnlyToolDefinitions(env, config), ...ownerToolDefinitions(env, baseUrl)]
      : readOnlyToolDefinitions(env, config);
    const handler = createMcp({
      serverInfo: { name: "anglesite-site", version: "1.0.0" },
      tools,
      authenticate: createMcpAuthenticator(env, baseUrl),
      protectedResourceMetadataUrl: `${baseUrl}/.well-known/oauth-protected-resource`,
    });
    return handler(request);
  };
}

export const handleMcp = createHandleMcp(mcpConfigArtifact as McpConfigArtifact);
