/** Runtime shape of `worker/mcp-config.json` (#1576) — generated by
 *  `scripts/mcp-artifact.ts` from `anglesite.json`'s `experimental.mcp` flag, mirroring how
 *  `worker/experiments.ts` defines the shape `scripts/experiments-artifact.ts` writes. */
export interface McpConfigArtifact {
  enabled: boolean;
  feedPaths: string[];
}
