/**
 * Read-only MCP server (#1576): a stateless Streamable HTTP endpoint at `/mcp`, backed by
 * Cloudflare's `createMcpHandler` (no Durable Objects — every tool here is derivable from
 * build-time-generated static artifacts). Gated behind `experimental.mcp`
 * (`worker/mcp-config.json`, generated by `scripts/mcp-artifact.ts`); returns a plain 404 when
 * off, exactly like an unclaimed route. See
 * docs/superpowers/specs/2026-08-19-site-mcp-server-design.md for the full design.
 */
import { McpServer } from "@modelcontextprotocol/server";
import { createMcpHandler } from "agents/mcp/server";
import { z } from "zod";
import { base64url } from "./token-signing.ts";
import type { WorkerEnv } from "./worker.ts";
import mcpConfigArtifact from "./mcp-config.json";
import type { McpConfigArtifact } from "./mcp-config.ts";
import { htmlToPlainText } from "../src/lib/html-to-plain-text.ts";
import { searchEntries, type McpSearchEntry } from "../src/lib/mcp-search-entries.ts";

const MCP_RATE_LIMIT_WINDOW_SECONDS = 3600;
const MCP_RATE_LIMIT_MAX_PER_WINDOW = 60;

/** Same shape as `worker.ts`'s `consentRateLimitKey`, but its own prefix — MCP tool-call traffic
 *  and IndieAuth consent-form submissions must not share a counter or a threshold. */
export async function mcpRateLimitKey(request: Request): Promise<string> {
  const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(ip));
  return `mcp-tool-call:${base64url(new Uint8Array(digest)).slice(0, 32)}`;
}

/** Same fail-closed shape as `worker.ts`'s `isConsentRateLimited`: an unbound `SOCIAL_KV` must
 *  never silently disable the limiter. A site with `experimental.mcp` on but no other social
 *  feature active still needs `SOCIAL_KV` provisioned — see `SocialWorkerProvisionCommand`. */
export async function isMcpRateLimited(request: Request, env: WorkerEnv): Promise<boolean> {
  if (!env.SOCIAL_KV) {
    console.warn(JSON.stringify({ event: "mcp.rate_limit_unavailable" }));
    return true;
  }
  const key = await mcpRateLimitKey(request);
  const raw = await env.SOCIAL_KV.get(key);
  const count = raw ? Number.parseInt(raw, 10) : 0;
  if (count >= MCP_RATE_LIMIT_MAX_PER_WINDOW) return true;
  await env.SOCIAL_KV.put(key, String(count + 1), { expirationTtl: MCP_RATE_LIMIT_WINDOW_SECONDS });
  return false;
}

/** Strips a trailing slash (except the bare root) and ensures a leading slash, so `"blog/x/"`,
 *  `"/blog/x"`, and `"/blog/x/"` all resolve to the same asset lookup. */
function normalizePagePath(path: string): string {
  const withLeadingSlash = path.startsWith("/") ? path : `/${path}`;
  return withLeadingSlash.length > 1 && withLeadingSlash.endsWith("/")
    ? withLeadingSlash.slice(0, -1)
    : withLeadingSlash;
}

async function fetchSearchIndex(env: WorkerEnv): Promise<McpSearchEntry[]> {
  if (!env.ASSETS) return [];
  const response = await env.ASSETS.fetch(new Request("https://internal.invalid/mcp-search-index.json"));
  if (!response.ok) return [];
  return (await response.json()) as McpSearchEntry[];
}

/** For a collection entry, the already-shipped `.md` mirror (`renderMarkdownMirror`,
 *  `[...slug].md.ts`) is tried first; anything else falls back to fetching the built HTML page
 *  and running `htmlToPlainText` on it. Both branches degrade to a plain "not found" string
 *  rather than throwing, matching the WebMCP tools' existing error-shape convention. */
async function fetchPageContent(path: string, env: WorkerEnv): Promise<string> {
  if (!env.ASSETS) return `Not found: ${path}`;
  const normalized = normalizePagePath(path);

  const mdResponse = await env.ASSETS.fetch(new Request(`https://internal.invalid${normalized}.md`));
  if (mdResponse.ok) return mdResponse.text();

  const htmlResponse = await env.ASSETS.fetch(new Request(`https://internal.invalid${normalized}`));
  if (!htmlResponse.ok) return `Not found: ${path}`;
  return htmlToPlainText(await htmlResponse.text());
}

function createSiteServer(env: WorkerEnv, config: McpConfigArtifact) {
  return () => {
    const server = new McpServer({ name: "anglesite-site", version: "1.0.0" });

    server.registerTool(
      "search_posts",
      {
        description: "Search this site's published posts by keyword",
        inputSchema: z.object({ query: z.string(), limit: z.number().int().min(1).max(20).optional() }),
      },
      async ({ query, limit }) => {
        const index = await fetchSearchIndex(env);
        const results = searchEntries(index, query, limit ?? 5);
        if (results.length === 0) {
          return { content: [{ type: "text" as const, text: `No results for "${query}".` }] };
        }
        const text = results.map((r) => `${r.title} — ${r.url}\n${r.excerpt}`).join("\n\n");
        return { content: [{ type: "text" as const, text }] };
      },
    );

    server.registerTool(
      "fetch_page_content",
      {
        description: "Fetch the readable content of one page on this site by its path",
        inputSchema: z.object({ path: z.string() }),
      },
      async ({ path }) => ({
        content: [{ type: "text" as const, text: await fetchPageContent(path, env) }],
      }),
    );

    server.registerTool(
      "list_feeds",
      { description: "List this site's syndication feed URLs" },
      async () => ({ content: [{ type: "text" as const, text: config.feedPaths.join("\n") }] }),
    );

    return server;
  };
}

function notFound(): Response {
  return new Response("Not Found", {
    status: 404,
    headers: { "content-type": "text/plain; charset=utf-8", "x-content-type-options": "nosniff" },
  });
}

/** Factory so tests can inject a config independent of the real build-time artifact — see
 *  `worker/worker.test.ts`. `handleMcp` below is the production handler, bound to the real
 *  generated `mcp-config.json`. */
export function createHandleMcp(config: McpConfigArtifact) {
  return async function handleMcp(request: Request, env: WorkerEnv, ctx: ExecutionContext): Promise<Response> {
    if (!config.enabled) return notFound();
    if (await isMcpRateLimited(request, env)) {
      return new Response("Too Many Requests", { status: 429 });
    }
    return createMcpHandler(createSiteServer(env, config), { route: "/mcp" })(request, env, ctx);
  };
}

export const handleMcp = createHandleMcp(mcpConfigArtifact as McpConfigArtifact);
