import Foundation
import Testing
@testable import AnglesiteCore

@Suite("LinkIntegrityGate")
struct LinkIntegrityGateTests {
    @Test("flags an internal href not present in internalRoutes")
    func flagsBrokenInternalLink() throws {
        let run = RichTextRun(kind: .link, text: "Read more", href: "/blog/missing")
        let paragraph = BlockNode(id: "p1", kind: .text, componentName: "p", props: [:], slots: [:], sourceSpan: [0, 0], richText: [run])
        let model = BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: ["p1"], blocks: ["p1": paragraph])
        let context = GateContext(resolvedTokens: [:], internalRoutes: ["/blog/hello-world"], assetRoot: URL(fileURLWithPath: "/tmp"))

        let findings = try LinkIntegrityGate.analyze(model: model, context: context)

        #expect(findings.map(\.id) == ["p1::linkIntegrity::richText.run.0"])
    }

    @Test("does not flag an internal href that resolves")
    func doesNotFlagResolvingLink() throws {
        let run = RichTextRun(kind: .link, text: "Read more", href: "/blog/hello-world")
        let paragraph = BlockNode(id: "p1", kind: .text, componentName: "p", props: [:], slots: [:], sourceSpan: [0, 0], richText: [run])
        let model = BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: ["p1"], blocks: ["p1": paragraph])
        let context = GateContext(resolvedTokens: [:], internalRoutes: ["/blog/hello-world"], assetRoot: URL(fileURLWithPath: "/tmp"))

        let findings = try LinkIntegrityGate.analyze(model: model, context: context)

        #expect(findings.isEmpty)
    }

    @Test("does not flag an external href — outside this gate's job")
    func doesNotFlagExternalLink() throws {
        let run = RichTextRun(kind: .link, text: "Anthropic", href: "https://anthropic.com")
        let paragraph = BlockNode(id: "p1", kind: .text, componentName: "p", props: [:], slots: [:], sourceSpan: [0, 0], richText: [run])
        let model = BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: ["p1"], blocks: ["p1": paragraph])
        let context = GateContext(resolvedTokens: [:], internalRoutes: [], assetRoot: URL(fileURLWithPath: "/tmp"))

        let findings = try LinkIntegrityGate.analyze(model: model, context: context)

        #expect(findings.isEmpty)
    }

    @Test("flags a broken href prop on an astro-kind link/button block")
    func flagsBrokenHrefProp() throws {
        let button = BlockNode(id: "btn1", kind: .astro, componentName: "Button", props: ["href": .string("/missing")], slots: [:], sourceSpan: [0, 0])
        let model = BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: ["btn1"], blocks: ["btn1": button])
        let context = GateContext(resolvedTokens: [:], internalRoutes: [], assetRoot: URL(fileURLWithPath: "/tmp"))

        let findings = try LinkIntegrityGate.analyze(model: model, context: context)

        #expect(findings.map(\.id) == ["btn1::linkIntegrity::hrefProp"])
    }

    @Test("does not flag a trailing-slash href against a slashless derived route")
    func doesNotFlagTrailingSlashLink() throws {
        // The shipped template links with trailing slashes throughout (`href="/blog/"`), while
        // route derivation emits `/blog` — an exact comparison called every one of them a 404.
        let model = Self.model(href: "/timeline/")
        let context = GateContext(resolvedTokens: [:], internalRoutes: ["/timeline"], assetRoot: URL(fileURLWithPath: "/tmp"))

        #expect(try LinkIntegrityGate.analyze(model: model, context: context).isEmpty)
    }

    @Test("ignores a query string or fragment when resolving an href")
    func ignoresQueryAndFragment() throws {
        let context = GateContext(resolvedTokens: [:], internalRoutes: ["/", "/about"], assetRoot: URL(fileURLWithPath: "/tmp"))

        #expect(try LinkIntegrityGate.analyze(model: Self.model(href: "/about?x=1"), context: context).isEmpty)
        #expect(try LinkIntegrityGate.analyze(model: Self.model(href: "/#contact"), context: context).isEmpty)
    }

    @Test("skips an href whose first segment names a dynamic-route directory")
    func skipsDynamicRouteTargets() throws {
        // `/blog/my-post` is generated by blog/[...slug].astro, which route derivation can't
        // enumerate without the content collection — so the gate declines to judge it either way.
        let model = Self.model(href: "/blog/my-post")
        let context = GateContext(
            resolvedTokens: [:], internalRoutes: ["/blog"], assetRoot: URL(fileURLWithPath: "/tmp"),
            dynamicRouteDirectories: ["blog"])

        #expect(try LinkIntegrityGate.analyze(model: model, context: context).isEmpty)
    }

    @Test("still flags a broken link outside any dynamic-route directory")
    func stillFlagsRealBreakage() throws {
        let model = Self.model(href: "/nope/")
        let context = GateContext(
            resolvedTokens: [:], internalRoutes: ["/blog"], assetRoot: URL(fileURLWithPath: "/tmp"),
            dynamicRouteDirectories: ["blog"])

        #expect(try LinkIntegrityGate.analyze(model: model, context: context).count == 1)
    }

    private static func model(href: String) -> BlockModel {
        let run = RichTextRun(kind: .link, text: "Read more", href: href)
        let paragraph = BlockNode(id: "p1", kind: .text, componentName: "p", props: [:], slots: [:], sourceSpan: [0, 0], richText: [run])
        return BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: ["p1"], blocks: ["p1": paragraph])
    }
}
