import Foundation
import Testing
import AnglesiteTestSupport
@testable import AnglesiteCore

/// Runs the quality gates against the **real** shipped template (`Resources/Template/`) rather
/// than a synthetic fixture. The per-checker suites all build their own `GateContext` by hand, so
/// nothing exercised the one shape that actually ships — which is how `LinkIntegrityGate` came to
/// flag essentially every link in the template as a 404 (trailing slashes, `.ts` endpoint routes
/// and dynamic-route targets all missed) without a single test noticing.
@Suite("Quality gates against Resources/Template")
struct QualityGatesTemplateTests {
    /// Every site-relative href the template's own pages/components/layouts author as a literal.
    /// Kept as a hand-maintained list on purpose: it's the assertion, and a drift here should be a
    /// deliberate edit, not something a glob quietly absorbs.
    private static let templateInternalHrefs = [
        "/",
        "/blog/",
        "/timeline/",
        "/resume/",
        "/tags/",
        "/search/",
        "/blog/rss.xml",
        "/rss.xml",
        "/atom.xml",
        "/feed.json",
        // Generated by [collection]/[...slug].astro — a bracketed *directory*, not just a bracketed
        // file inside a plain one. Regression case for the dynamicRouteDirectories bracket-stripping
        // fix: without it, "collection" here is compared against the stored literal "[collection]"
        // and never matches, so this link false-flags as a 404.
        "/notes/some-note",
    ]

    @Test("internalRoutes covers the template's static pages and .ts endpoint routes")
    func routesCoverKnownTemplatePages() throws {
        let context = GateContext.build(fromSourceDirectory: try templateRoot())

        #expect(context.internalRoutes.contains("/"))
        #expect(context.internalRoutes.contains("/resume"))
        #expect(context.internalRoutes.contains("/search"))
        #expect(context.internalRoutes.contains("/timeline"))
        #expect(context.internalRoutes.contains("/about"))
        #expect(context.internalRoutes.contains("/community/about"))
        #expect(context.internalRoutes.contains("/rss.xml"))
        #expect(context.internalRoutes.contains("/atom.xml"))
        #expect(context.internalRoutes.contains("/feed.json"))
        #expect(context.internalRoutes.contains("/sitemap.xml"))
        // Generated by [collection]/[...slug].astro and blog/[...slug].astro — never enumerable
        // from the filesystem alone, so they must not be in the set.
        #expect(!context.internalRoutes.contains("/blog/hello-world"))
    }

    @Test("dynamicRouteDirectories names the template's bracketed subtrees")
    func dynamicDirectoriesCoverBracketedSubtrees() throws {
        let context = GateContext.build(fromSourceDirectory: try templateRoot())

        #expect(context.dynamicRouteDirectories.contains("blog"))
        #expect(context.dynamicRouteDirectories.contains("tags"))
        // [collection]/[...slug].astro is a bracketed *directory* — "collection" is a route
        // parameter (any of the site's content collections), never a literal href segment, so this
        // records the wildcard sentinel rather than a name nothing will ever match.
        #expect(context.dynamicRouteDirectories.contains(GateContext.rootLevelDynamicSentinel))
    }

    @Test("LinkIntegrityGate produces no finding for any link the template itself authors")
    func templateOwnLinksAreNeverFlagged() throws {
        let context = GateContext.build(fromSourceDirectory: try templateRoot())
        var blocks: [BlockId: BlockNode] = [:]
        var rootIds: [BlockId] = []
        for (index, href) in Self.templateInternalHrefs.enumerated() {
            let id = "link\(index)"
            let run = RichTextRun(kind: .link, text: href, href: href)
            blocks[id] = BlockNode(
                id: id, kind: .text, componentName: "p", props: [:], slots: [:], sourceSpan: [0, 0], richText: [run])
            rootIds.append(id)
        }
        let model = BlockModel(path: "src/pages/index.astro", version: "v1", rootIds: rootIds, blocks: blocks)

        let findings = try LinkIntegrityGate.analyze(model: model, context: context)

        #expect(findings.map(\.message) == [])
    }

    @Test("ContrastGate reads the template's light palette, not its dark-scheme override")
    func contrastReadsLightPalette() throws {
        let context = GateContext.build(fromSourceDirectory: try templateRoot())

        #expect(context.resolvedTokens["color-text"] == "#1e293b")
        #expect(context.resolvedTokens["color-background"] == "#ffffff")
        #expect(context.resolvedTokens["color-surface"] == "#f8fafc")
    }
}
