import {
  SEARCH_POSTS_TOOL,
  FETCH_POST_MARKDOWN_TOOL,
  searchPosts,
  fetchPostMarkdown,
  type PagefindModule,
  type WebmcpToolDefinition,
  type WebmcpToolResult,
} from "../lib/webmcp-tools.ts";

interface ModelContextTool extends WebmcpToolDefinition {
  execute(args: any): Promise<WebmcpToolResult>;
}

interface ModelContext {
  registerTool(def: ModelContextTool, options?: { signal?: AbortSignal }): Promise<void>;
}

declare global {
  interface Document {
    modelContext?: ModelContext;
  }
}

if ("modelContext" in document && document.modelContext) {
  const modelContext = document.modelContext;
  // Held for the page's lifetime — this script never unregisters its own tools, so the
  // controller is never aborted; it exists only because registerTool's options accept one.
  const controller = new AbortController();

  async function registerSafely(
    def: WebmcpToolDefinition,
    execute: (args: any) => Promise<WebmcpToolResult>,
  ): Promise<void> {
    try {
      await modelContext.registerTool({ ...def, execute }, { signal: controller.signal });
    } catch (err) {
      // No verified way exists to detect Cloudflare's edge-injected WebMCP bridge ahead of
      // time (see the design spec's "Dedupe strategy") — if the platform or another pack
      // throws on a duplicate tool name, log and move on rather than breaking the page.
      console.warn(`[webmcp] failed to register tool "${def.name}":`, err);
    }
  }

  void registerSafely(SEARCH_POSTS_TOOL, (args) =>
    searchPosts(args, () => {
      // @ts-expect-error ts(2307): "/pagefind/pagefind.js" is generated by this project's
      // `postbuild` step (`npx pagefind --site dist`), so it can never exist on disk for
      // TypeScript to resolve at check time — no ambient `declare module` can fix this, since
      // TS rejects any ambient module name that looks like a relative/rooted path (ts(2436)).
      // `/* @vite-ignore */` only stops Vite from trying to resolve/bundle it; it has no effect
      // on this diagnostic. The result is cast to `PagefindModule` below to keep everything
      // past this line fully typed.
      return import(/* @vite-ignore */ "/pagefind/pagefind.js") as unknown as Promise<PagefindModule>;
    }),
  );

  void registerSafely(FETCH_POST_MARKDOWN_TOOL, (args) => fetchPostMarkdown(args, fetch));
}
