import Foundation

public enum AttributionCatalogError: Error, Equatable {
    /// The app bundle has no `Resources/Attributions/<source>.json` (missing resource, or the
    /// process's `Bundle.main` isn't the app bundle at all — e.g. inside `swift test`).
    case resourceMissing(AttributionSource)
    /// The manifest file exists but isn't valid `[OSSAttribution]` JSON.
    case decodingFailed(AttributionSource)
}

/// Loads the generated, checked-in attribution manifests (see
/// docs/superpowers/specs/2026-07-31-oss-attributions-design.md). Manifests are generated by
/// `scripts/generate-attributions.sh` and committed under `Resources/Attributions/`.
public enum AttributionCatalog {
    /// Loads `Resources/Attributions/<source>.json` from `bundle`'s resource directory.
    public static func load(_ source: AttributionSource, bundle: Bundle = .main) throws -> [OSSAttribution] {
        guard let resourceURL = bundle.resourceURL,
              let data = try? Data(contentsOf: resourceURL.appendingPathComponent("Attributions/\(source.rawValue).json"))
        else {
            throw AttributionCatalogError.resourceMissing(source)
        }
        return try decode(data, source: source)
    }

    static func decode(_ data: Data, source: AttributionSource) throws -> [OSSAttribution] {
        do {
            return try JSONDecoder().decode([OSSAttribution].self, from: data)
        } catch {
            throw AttributionCatalogError.decodingFailed(source)
        }
    }
}
