import Foundation

/// The site-settings representation of the RFC 9116 `security.txt` generated by the template.
///
/// Owns exactly two `.site-config` keys — `SECURITY_CONTACT` (a preference-ordered,
/// comma-separated contact list) and `SECURITY_TXT_MODE`. Contact *validity* stays the
/// template generator's job (`normalizeSecurityContact` in `scripts/edge-artifacts.ts`): this
/// type normalizes shape only, so an entry the generator would reject is written through and
/// reported by the build rather than silently deleted on save.
public enum SecurityReportingAsset {
    /// Mirrors the template's `SecurityTxtMode`.
    public enum Mode: String, Sendable, CaseIterable, Identifiable, Equatable {
        /// The template generates `security.txt` from the configured contacts on each build.
        case generated
        /// The owner hand-maintains `security.txt`; the template (and the app's settings UI)
        /// leave the published file alone.
        case manual
        /// No `security.txt` is published at all — the owner has opted out.
        case disabled

        /// `Identifiable` by case so SwiftUI pickers can bind `allCases` directly.
        public var id: Self { self }
    }

    /// The editable pair the Website Settings ▸ Security Reports UI binds to — one value type
    /// so save/dirty comparisons cover both keys at once.
    public struct Settings: Sendable, Equatable {
        /// Preference-ordered contacts, one per line in the UI; comma-joined in `.site-config`.
        public var contacts: String
        /// How (or whether) the template publishes `security.txt` on the next build.
        public var mode: Mode

        /// Defaults mirror a site with nothing configured: no contacts, nothing published
        /// until the owner opts in.
        public init(contacts: String = "", mode: Mode = .disabled) {
            self.contacts = contacts
            self.mode = mode
        }
    }

    /// Reads this type's two `.site-config` keys out of a raw config string. Deliberately
    /// tolerant: an unset or unrecognized mode is inferred from whether a contact exists at all
    /// (matching the template's `resolveSecurityTxtMode`), so a site scaffolded before
    /// `SECURITY_TXT_MODE` existed never reads as having turned `security.txt` off.
    public static func parseSettings(from config: String) -> Settings {
        let stored = SiteConfigFile.value(forKey: "SECURITY_CONTACT", in: config) ?? ""
        // An unset or unrecognized mode mirrors the template's `resolveSecurityTxtMode`: infer
        // from whether a contact is configured at all, so a site scaffolded before the key
        // existed doesn't appear to have silently turned security.txt off.
        let mode = Mode(rawValue: SiteConfigFile.value(forKey: "SECURITY_TXT_MODE", in: config) ?? "")
            ?? (stored.trimmingCharacters(in: .whitespaces).isEmpty ? .disabled : .generated)
        return Settings(contacts: decodeStored(stored).joined(separator: "\n"), mode: mode)
    }

    /// Upserts both keys into the site's `.site-config`, normalizing contact shape (but not
    /// validity — see the type doc) on the way through. Skips the write entirely when the
    /// result is byte-identical, so re-saving an untouched settings sheet never dirties the
    /// site's git working tree.
    public static func install(_ settings: Settings, siteDirectory: URL) throws {
        let configURL = siteDirectory.appendingPathComponent(WebsiteAnalyticsAsset.configRelativePath)
        let config = (try? String(contentsOf: configURL, encoding: .utf8)) ?? ""
        let updated = SiteConfigFile.upsert([
            ("SECURITY_CONTACT", encodeStored(normalizedContacts(settings.contacts))),
            ("SECURITY_TXT_MODE", settings.mode.rawValue),
        ], into: config)
        guard updated != config else { return }
        try updated.write(to: configURL, atomically: true, encoding: .utf8)
    }

    /// Shape normalization of the UI's newline-separated text: trim, drop blanks, collapse
    /// duplicates, preserve order. Deliberately does not judge whether an entry is a usable
    /// RFC 9116 contact URI — see this type's doc comment.
    ///
    /// Splits on newlines only. A comma is a list separator in `.site-config`, not in the UI,
    /// and an entry may legitimately contain one — splitting here would break it apart.
    public static func normalizedContacts(_ raw: String) -> [String] {
        var result: [String] = []
        for part in raw.split(whereSeparator: { $0.isNewline }) {
            let value = part.trimmingCharacters(in: .whitespaces)
            if !value.isEmpty, !result.contains(value) { result.append(value) }
        }
        return result
    }

    /// Splits the stored `.site-config` value into entries, restoring escaped commas.
    ///
    /// Only `%2C` is decoded — a general percent-decode would turn an ordinary `%20` in a URL
    /// into a space and corrupt every contact written before this escaping existed. This is the
    /// exact inverse of `encodeStored`, and matches the template's `unescapeContactComma`.
    public static func decodeStored(_ stored: String) -> [String] {
        var result: [String] = []
        for part in stored.split(separator: ",", omittingEmptySubsequences: true) {
            let value = part.trimmingCharacters(in: .whitespaces)
                .replacingOccurrences(of: "%2C", with: ",", options: [.caseInsensitive])
            if !value.isEmpty, !result.contains(value) { result.append(value) }
        }
        return result
    }

    /// Joins entries into the stored `.site-config` value, escaping any comma inside an entry so
    /// the split can never truncate a contact URI. A comma is legal in a URI path or query
    /// (RFC 3986) and inside a quoted local part (RFC 5321).
    public static func encodeStored(_ entries: [String]) -> String {
        entries
            .map { $0.replacingOccurrences(of: ",", with: "%2C") }
            .joined(separator: ",")
    }

    /// The repo's private advisory form. `RemoteRepo` is GitHub-by-construction
    /// (`RemoteRepo.parse` rejects every other host), so this needs no host check of its own.
    public static func advisoryURL(for repo: RemoteRepo) -> URL {
        repo.url.appendingPathComponent("security/advisories/new")
    }

    /// True when `contacts` already lists this repo's advisory form.
    public static func usesAdvisoryForm(_ contacts: String, repo: RemoteRepo) -> Bool {
        normalizedContacts(contacts).contains(advisoryURL(for: repo).absoluteString)
    }

    /// `contacts` with the advisory form as the most-preferred entry, preserving the rest in
    /// order and never duplicating a form that is already listed.
    public static func prependingAdvisoryForm(_ contacts: String, repo: RemoteRepo) -> String {
        let form = advisoryURL(for: repo).absoluteString
        return ([form] + normalizedContacts(contacts).filter { $0 != form }).joined(separator: "\n")
    }
}
