import Foundation

/// Deterministic markdown rendering of a `SocialMediaPlan` into the site repo's
/// `docs/social-calendar.md` — the same git-visible contract the markdown skill kept, so the
/// plan is portable and survives editing outside the app. Anglesite never posts on the
/// owner's behalf; the calendar is a copy-paste companion.
public enum SocialCalendarMarkdown {
    static let dateFormatter: DateFormatter = {
        let f = DateFormatter()
        f.dateFormat = "yyyy-MM-dd"
        f.locale = Locale(identifier: "en_US_POSIX")
        f.timeZone = TimeZone(identifier: "UTC")
        return f
    }()

    /// FM-generated text goes into table cells — escape pipes and flatten line endings (`\n`,
    /// `\r\n`, and a lone `\r` are all line endings per CommonMark) so a stray "|" or newline
    /// can't split the row.
    private static func cell(_ text: String) -> String {
        text.replacingOccurrences(of: "|", with: "\\|")
            .replacingOccurrences(of: "\r\n", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
    }

    /// Renders the plan as the full `social-calendar.md` document: platform cadence table,
    /// per-platform bios (a missing bio is marked, never silently skipped), content pillars,
    /// then one table per week. Pure string building — pair with ``write(markdown:sourceDirectory:fileManager:)``
    /// to put it on disk, and keep the two separate so tests can assert on output without I/O.
    public static func render(plan: SocialMediaPlan, siteName: String) -> String {
        var out: [String] = []
        out.append("# Social media plan for \(siteName)")
        out.append("")
        out.append("> Generated by Anglesite. Anglesite never posts on your behalf — copy-paste what you like, edit what you don't.")
        out.append("")
        out.append("## Platforms")
        out.append("")
        out.append("| Platform | Posts/week | Why |")
        out.append("|---|---|---|")
        for p in plan.platforms {
            out.append("| \(cell(p.platform)) | \(p.postsPerWeek) | \(cell(p.note)) |")
        }
        out.append("")
        out.append("## Profile bios")
        out.append("")
        for p in plan.platforms {
            out.append("**\(p.platform)** (max \(p.bioCharLimit) chars): \(plan.bios[p.platform] ?? "_(no bio generated)_")")
            out.append("")
        }
        out.append("## Content pillars")
        out.append("")
        for pillar in plan.pillars {
            out.append("- **\(pillar.name)** — \(pillar.detail)")
        }
        out.append("")
        for week in plan.weeks {
            out.append("## Week of \(dateFormatter.string(from: week.startDate))")
            out.append("")
            out.append("| Day | Platform | Pillar | Idea |")
            out.append("|---|---|---|---|")
            for e in week.entries {
                out.append("| \(cell(e.day)) | \(cell(e.platform)) | \(cell(e.pillar)) | \(cell(e.idea)) |")
            }
            out.append("")
        }
        return out.joined(separator: "\n")
    }

    /// Writes (or replaces) `docs/social-calendar.md` under the site's `Source/` tree.
    @discardableResult
    public static func write(markdown: String, sourceDirectory: URL,
                             fileManager: FileManager = .default) throws -> URL {
        let docs = sourceDirectory.appendingPathComponent("docs")
        try fileManager.createDirectory(at: docs, withIntermediateDirectories: true)
        let url = docs.appendingPathComponent("social-calendar.md")
        try markdown.write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
