#!/usr/bin/env bash
#
# Pin the `davidwkeith/workers` manifests the app fetches at run time (#1961, decision D7 in
# docs/specs/2026-09-08-product-direction-review-decisions.md).
#
# `WorkerCatalogFetcher` (catalog.json — worker descriptors + route claims that feed the deploy
# pipeline) and `WorkersConformanceFetcher` (conformance/status.json — advisory only) used to
# fetch from that repo's floating `main` branch, so a compromise of the branch reached every
# user's next deploy. They now fetch from a pinned commit and verify a SHA-256 digest before
# trusting the bytes. Both the commit and the digests live in scripts/worker-catalog.lock.json
# (same pattern as scripts/container-artifact-versions.lock.json), and this script is the only
# thing that bumps them — a deliberate, reviewed step, never something the app does on its own.
#
# The lock is metadata for humans and for this script; the app reads the pin from
# Sources/AnglesiteCore/Cloudflare/WorkerCatalogPin.swift, which this script regenerates from the
# lock so the two can never drift silently (`--check` fails when they disagree, and CI runs it
# through scripts/bump-worker-catalog.test.sh in the linux-build-test lane).
#
# Usage:
#   scripts/bump-worker-catalog.sh                # pin davidwkeith/workers `main` HEAD
#   scripts/bump-worker-catalog.sh <commit-sha>   # pin a specific 40-hex commit
#   scripts/bump-worker-catalog.sh --regenerate   # rewrite WorkerCatalogPin.swift from the lock (no network)
#   scripts/bump-worker-catalog.sh --check        # verify WorkerCatalogPin.swift matches the lock (no network)
#
# A bump prints a unified diff of catalog.json / conformance/status.json between the previous
# and new pins so the reviewer sees exactly what the app will start trusting. Review that diff,
# then commit the lock and the regenerated Swift file together.
#
# Overrides (used by the test): WORKER_CATALOG_LOCK_FILE, WORKER_CATALOG_PIN_SWIFT,
# WORKER_CATALOG_RAW_BASE (defaults to https://raw.githubusercontent.com),
# WORKER_CATALOG_GIT_REMOTE (defaults to https://github.com/davidwkeith/workers.git).
# Network access goes through `curl` and `git ls-remote` on PATH, nothing else.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

REPOSITORY="davidwkeith/workers"
CATALOG_PATH="catalog.json"
CONFORMANCE_STATUS_PATH="conformance/status.json"

LOCK_FILE="${WORKER_CATALOG_LOCK_FILE:-$ROOT/scripts/worker-catalog.lock.json}"
PIN_SWIFT="${WORKER_CATALOG_PIN_SWIFT:-$ROOT/Sources/AnglesiteCore/Cloudflare/WorkerCatalogPin.swift}"
RAW_BASE="${WORKER_CATALOG_RAW_BASE:-https://raw.githubusercontent.com}"
GIT_REMOTE="${WORKER_CATALOG_GIT_REMOTE:-https://github.com/$REPOSITORY.git}"

usage() {
    sed -n '/^# Usage:/,/^#$/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

sha256_of() {
    # macOS ships `shasum` (Perl, always present) but not GNU `sha256sum`; the swift:*-noble CI
    # image has both. Prefer sha256sum when present.
    if command -v sha256sum >/dev/null 2>&1; then
        sha256sum "$1" | awk '{print $1}'
    else
        shasum -a 256 "$1" | awk '{print $1}'
    fi
}

is_sha256() { [[ "$1" =~ ^[0-9a-f]{64}$ ]]; }
is_commit() { [[ "$1" =~ ^[0-9a-f]{40}$ ]]; }
is_date() { [[ "$1" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; }

# lock_read <key> — the lock is deliberately flat (one string value per line) so it can be read
# with sed alone: the CI image that runs the test has no jq or python.
lock_read() {
    [[ -f "$LOCK_FILE" ]] || die "missing lock file $LOCK_FILE"
    local value
    value="$(sed -n "s/^[[:space:]]*\"$1\":[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$LOCK_FILE" | head -n 1)"
    [[ -n "$value" ]] || die "lock file $LOCK_FILE has no \"$1\" entry"
    printf '%s' "$value"
}

# lock_write <commit> <catalog sha256> <conformance sha256> <pinned_at>
lock_write() {
    local tmp
    tmp="$(mktemp)"
    cat >"$tmp" <<EOF
{
  "_comment": "Pinned davidwkeith/workers commit and SHA-256 digests of the manifests the app fetches at run time (#1961, decision D7). Written only by scripts/bump-worker-catalog.sh, which also regenerates Sources/AnglesiteCore/Cloudflare/WorkerCatalogPin.swift from it; scripts/bump-worker-catalog.sh --check fails when the two disagree. Committed (not gitignored) — this is metadata, not a vendored artifact.",
  "repository": "$REPOSITORY",
  "commit": "$1",
  "catalog_path": "$CATALOG_PATH",
  "catalog_sha256": "$2",
  "conformance_status_path": "$CONFORMANCE_STATUS_PATH",
  "conformance_status_sha256": "$3",
  "pinned_at": "$4"
}
EOF
    mv "$tmp" "$LOCK_FILE"
}

# render_swift <commit> <catalog sha256> <conformance sha256> <pinned_at> — the exact bytes of
# WorkerCatalogPin.swift for those values. Keep this the only place that knows the file's shape.
render_swift() {
    cat <<EOF
// GENERATED by scripts/bump-worker-catalog.sh from scripts/worker-catalog.lock.json — do not
// edit by hand. Re-run the script to bump the pin; \`scripts/bump-worker-catalog.sh --check\`
// (CI, linux-build-test lane) fails when this file and the lock disagree.

/// The pinned \`davidwkeith/workers\` commit and the SHA-256 digests of the two manifests the app
/// fetches from it at run time (#1961, decision D7). \`WorkerCatalogFetcher\` and
/// \`WorkersConformanceFetcher\` build their URLs from \`\`commit\`\` (never a branch name) and refuse
/// a response whose digest doesn't match, so a compromise of that repository's \`main\` branch —
/// or of the CDN in front of it — can't reach a user's deploy without a deliberate, reviewed bump
/// here. See \`docs/architecture.md\` ▸ "First-party infrastructure".
public enum WorkerCatalogPin {
    /// GitHub \`owner/name\` of the monorepo that publishes the manifests.
    public static let repository = "$REPOSITORY"
    /// The pinned 40-hex commit. Manifests are fetched at this commit, never at a branch.
    public static let commit = "$1"
    /// ISO-8601 date the pin was last bumped (informational; from the lock).
    public static let pinnedAt = "$4"
    /// Repo-relative path of the worker catalog manifest.
    public static let catalogPath = "$CATALOG_PATH"
    /// Lowercase-hex SHA-256 of the catalog manifest bytes at \`\`commit\`\`.
    public static let catalogSHA256 = "$2"
    /// Repo-relative path of the conformance status manifest.
    public static let conformanceStatusPath = "$CONFORMANCE_STATUS_PATH"
    /// Lowercase-hex SHA-256 of the conformance status manifest bytes at \`\`commit\`\`.
    public static let conformanceStatusSHA256 = "$3"
}
EOF
}

validate_values() {
    is_commit "$1" || die "commit must be a 40-character lowercase hex SHA, got: $1"
    is_sha256 "$2" || die "catalog_sha256 must be 64 lowercase hex characters, got: $2"
    is_sha256 "$3" || die "conformance_status_sha256 must be 64 lowercase hex characters, got: $3"
    is_date "$4" || die "pinned_at must be YYYY-MM-DD, got: $4"
}

read_lock_values() {
    LOCK_COMMIT="$(lock_read commit)"
    LOCK_CATALOG_SHA="$(lock_read catalog_sha256)"
    LOCK_STATUS_SHA="$(lock_read conformance_status_sha256)"
    LOCK_PINNED_AT="$(lock_read pinned_at)"
    [[ "$(lock_read repository)" == "$REPOSITORY" ]] || die "lock repository is not $REPOSITORY"
    [[ "$(lock_read catalog_path)" == "$CATALOG_PATH" ]] || die "lock catalog_path is not $CATALOG_PATH"
    [[ "$(lock_read conformance_status_path)" == "$CONFORMANCE_STATUS_PATH" ]] \
        || die "lock conformance_status_path is not $CONFORMANCE_STATUS_PATH"
    validate_values "$LOCK_COMMIT" "$LOCK_CATALOG_SHA" "$LOCK_STATUS_SHA" "$LOCK_PINNED_AT"
}

write_swift_from_lock() {
    local tmp
    tmp="$(mktemp)"
    render_swift "$LOCK_COMMIT" "$LOCK_CATALOG_SHA" "$LOCK_STATUS_SHA" "$LOCK_PINNED_AT" >"$tmp"
    mkdir -p "$(dirname "$PIN_SWIFT")"
    mv "$tmp" "$PIN_SWIFT"
}

do_check() {
    read_lock_values
    [[ -f "$PIN_SWIFT" ]] || die "missing $PIN_SWIFT — run scripts/bump-worker-catalog.sh --regenerate"
    local expected
    expected="$(mktemp)"
    render_swift "$LOCK_COMMIT" "$LOCK_CATALOG_SHA" "$LOCK_STATUS_SHA" "$LOCK_PINNED_AT" >"$expected"
    if ! diff -u "$PIN_SWIFT" "$expected" >&2; then
        rm -f "$expected"
        die "$PIN_SWIFT does not match $LOCK_FILE — run scripts/bump-worker-catalog.sh --regenerate and commit the result"
    fi
    rm -f "$expected"
    echo "worker catalog pin: OK ($REPOSITORY@${LOCK_COMMIT:0:12}, pinned $LOCK_PINNED_AT)"
}

do_regenerate() {
    read_lock_values
    write_swift_from_lock
    echo "regenerated $PIN_SWIFT from $LOCK_FILE ($REPOSITORY@${LOCK_COMMIT:0:12})"
}

# fetch_raw <commit> <path> <out> — one file at one commit, via raw.githubusercontent.com (or
# the override). `curl -f` turns a 404 into a non-zero exit so a typo'd commit can't be pinned.
fetch_raw() {
    curl -fsSL --retry 3 --retry-delay 1 "$RAW_BASE/$REPOSITORY/$1/$2" -o "$3"
}

resolve_main_head() {
    local line
    line="$(git ls-remote "$GIT_REMOTE" refs/heads/main)" || die "git ls-remote $GIT_REMOTE failed"
    local sha
    sha="$(printf '%s\n' "$line" | awk 'NR == 1 {print $1}')"
    is_commit "$sha" || die "could not resolve refs/heads/main from $GIT_REMOTE (got: ${line:-<empty>})"
    printf '%s' "$sha"
}

# show_diff <old commit> <new commit> <path> <new file> — best-effort review aid: the previous
# pin's copy may be unreachable (offline history rewrite), which must not fail the bump.
show_diff() {
    local old_file
    old_file="$(mktemp)"
    if fetch_raw "$1" "$3" "$old_file" 2>/dev/null; then
        echo "--- $3: $REPOSITORY@${1:0:12} -> @${2:0:12}"
        diff -u --label "$3@${1:0:12}" --label "$3@${2:0:12}" "$old_file" "$4" || true
    else
        echo "--- $3: previous pin @${1:0:12} not fetchable, skipping diff"
    fi
    rm -f "$old_file"
}

do_bump() {
    local commit="${1:-}"
    if [[ -z "$commit" ]]; then
        commit="$(resolve_main_head)"
        echo "resolved $REPOSITORY main -> $commit"
    fi
    is_commit "$commit" || die "commit must be a 40-character lowercase hex SHA, got: $commit"

    local previous_commit=""
    if [[ -f "$LOCK_FILE" ]]; then
        previous_commit="$(lock_read commit)"
    fi

    # Global (not local) so the EXIT trap can still see it after this function returns.
    WORK_DIR="$(mktemp -d)"
    trap 'rm -rf "$WORK_DIR"' EXIT
    local work="$WORK_DIR"
    mkdir -p "$work/$(dirname "$CONFORMANCE_STATUS_PATH")"

    fetch_raw "$commit" "$CATALOG_PATH" "$work/$CATALOG_PATH" \
        || die "could not fetch $CATALOG_PATH at $REPOSITORY@$commit — lock left untouched"
    fetch_raw "$commit" "$CONFORMANCE_STATUS_PATH" "$work/$CONFORMANCE_STATUS_PATH" \
        || die "could not fetch $CONFORMANCE_STATUS_PATH at $REPOSITORY@$commit — lock left untouched"

    local catalog_sha status_sha pinned_at
    catalog_sha="$(sha256_of "$work/$CATALOG_PATH")"
    status_sha="$(sha256_of "$work/$CONFORMANCE_STATUS_PATH")"
    pinned_at="$(date -u +%Y-%m-%d)"

    if [[ -n "$previous_commit" && "$previous_commit" != "$commit" ]] && is_commit "$previous_commit"; then
        show_diff "$previous_commit" "$commit" "$CATALOG_PATH" "$work/$CATALOG_PATH"
        show_diff "$previous_commit" "$commit" "$CONFORMANCE_STATUS_PATH" "$work/$CONFORMANCE_STATUS_PATH"
    elif [[ "$previous_commit" == "$commit" ]]; then
        echo "already pinned to $REPOSITORY@$commit — refreshing digests and the generated Swift file"
    fi

    lock_write "$commit" "$catalog_sha" "$status_sha" "$pinned_at"
    read_lock_values
    write_swift_from_lock

    echo "pinned $REPOSITORY@$commit ($pinned_at)"
    echo "  $CATALOG_PATH: $catalog_sha"
    echo "  $CONFORMANCE_STATUS_PATH: $status_sha"
    echo "wrote $LOCK_FILE and $PIN_SWIFT — review the diff above and commit both together"
}

case "${1:-}" in
    -h | --help)
        usage
        exit 0
        ;;
    --check)
        [[ $# -eq 1 ]] || die "--check takes no other arguments"
        do_check
        ;;
    --regenerate)
        [[ $# -eq 1 ]] || die "--regenerate takes no other arguments"
        do_regenerate
        ;;
    --*)
        die "unknown option: $1 (see --help)"
        ;;
    *)
        [[ $# -le 1 ]] || die "expected at most one commit SHA argument (see --help)"
        do_bump "${1:-}"
        ;;
esac
